// Issue #3: Receipts. Abdul El-Sayed's record.
//
// Same format as panels.js. Panels with `type: "stat"` are drawn by the page
// and need no art. Facts checked against the sources as of September 27, 2026.
// Where one of his own claims has been fact-checked, the comic uses the
// checked figure and the back matter shows the verdict.

export const PAGES = [
  {
    label: "Part 1",
    chapter: "Five employees",
    intro: "In 2015 Detroit was just out of bankruptcy, and its health department barely existed.",
    panels: [
      {
        id: "e01",
        where: "detroit",
        size: "wide",
        splash: true,
        tag: "Detroit · Aug 2015",
        scene: "What's left",
        art: null,
        alt: "Five desks in a big empty office, stacks of contractor folders.",
        captions: [
          { text: "In 2012 the city handed most of its health department to an outside nonprofit. By 2015 the department is five city employees and 85 contractors.", pos: "tl" },
          { text: "The new director is a 30-year-old epidemiologist with a starting budget of about $1 million.", pos: "bl" },
        ],
        cites: [1, 2],
        prompt: "Wide 16:9 splash. A cavernous, dusty Detroit city office: only five occupied desks in a sea of empty ones, stacks of manila contractor folders, a dead potted plant, sunlight through tall grimy windows. A young Egyptian-American man in a suit stands in the doorway taking it in, sleeves about to be rolled up. Blue shadows, gold shaft of light.",
      },
      {
        id: "e02",
        where: "detroit",
        size: "third",
        type: "stat",
        tag: "18 months later",
        big: "~220",
        label: "city health workers when he left",
        sub: "Up from five, reorganized into teams for mothers, kids and adults.",
        cites: [2, 1],
      },
      {
        id: "e03",
        where: "detroit",
        size: "two-thirds",
        tag: "Detroit · 2016",
        scene: "Back to basics",
        art: null,
        alt: "A mobile eye clinic and a new team of health workers outside a Detroit school.",
        captions: [
          { text: "The rebuilt department restarts services that had lapsed: blood-lead testing for young kids, and free eye exams and glasses for schoolkids through a mobile clinic.", pos: "tl" },
        ],
        cites: [3, 4],
        prompt: "Wide 2:1. A sunny morning outside a Detroit elementary school: a mobile eye-clinic van with its door open, kids lined up, a nurse fitting glasses on a grinning girl, city health workers in new department polo shirts with clipboards. Bright gold and Detroit blue.",
      },
    ],
  },
  {
    label: "Part 2",
    chapter: "48217",
    intro: "Southwest Detroit's 48217 is the most polluted ZIP code in Michigan. It sits next to an oil refinery.",
    panels: [
      {
        id: "e04",
        where: "detroit",
        size: "two-thirds",
        tag: "Southwest Detroit · Jan 2016",
        scene: "The church hall",
        art: null,
        alt: "Residents packed into a church hall, refinery flares visible through the window.",
        captions: [
          { text: "Marathon Petroleum wants a permit to release more sulfur dioxide from its refinery. The health director publicly opposes it.", pos: "tl" },
        ],
        bubbles: [
          { who: "El-Sayed", text: "People have been submitting stories to us about living in that ZIP code, and they are heartbreaking.", pos: "right low" },
        ],
        cites: [5, 6],
        prompt: "Wide 2:1. A packed church hall in Southwest Detroit at night: Black and Latino residents in folding chairs, a mother holding a child's asthma inhaler, an older woman activist standing to speak. Through the stained-glass window, orange refinery flares glow. A young Egyptian-American health director stands at the mic. Warm gold interior, orange flare, deep blue night.",
      },
      {
        id: "e05",
        where: "detroit",
        size: "third",
        type: "stat",
        tag: "March 2016",
        big: "−20%",
        label: "in the refinery's permitted sulfur dioxide",
        sub: "Marathon revised its plan after the backlash. New federal pollution rules pushed too.",
        cites: [6, 5],
      },
    ],
  },
  {
    label: "Part 3",
    chapter: "Lead",
    intro: "Months after the Flint crisis broke, Detroit started checking its own kids.",
    panels: [
      {
        id: "e06",
        where: "detroit",
        size: "half",
        tall: true,
        tag: "Detroit schools · Spring 2016",
        scene: "The fountains",
        art: null,
        alt: "A health worker holds a sample vial under a school drinking fountain while a kid watches.",
        captions: [
          { text: "His department and the city test the water in 62 Detroit elementary schools. 19 come back with elevated lead or copper. One fountain is 100 times over the limit.", pos: "tl" },
          { text: "He recommends every student under 6 get a blood-lead test.", pos: "bl" },
        ],
        cites: [7, 8],
        prompt: "Portrait 3:4. An old Detroit school hallway, a young Egyptian-American doctor crouched at a drinking fountain holding a sample vial up to the light, a curious second-grader in a backpack watching beside him. A wall map behind them pinned with red dots. Cool fluorescent blue with warm gold highlights.",
      },
      {
        id: "e07",
        where: "detroit",
        size: "half",
        type: "stat",
        tag: "Testing restarts",
        big: "5,876",
        label: "young kids tested in a single quarter of 2016",
        sub: "The share with high lead rose, because kids who had gone untested were finally being checked.",
        cites: [9],
      },
      {
        id: "e08",
        where: "detroit",
        size: "half",
        type: "stat",
        tag: "His department's study",
        big: "+20%",
        label: "higher odds of lead poisoning for kids living near a demolition",
        sub: "From a study of 50,904 Detroit children. With two or more demolitions nearby: +38%.",
        cites: [10],
      },
      {
        id: "e09",
        where: "detroit",
        size: "wide",
        tag: "2017–2018",
        scene: "Not finished",
        art: null,
        alt: "Water fountains covered with bags in a school hallway.",
        captions: [
          { text: "He tested for the problem and exposed it. Fixing it took longer: after he left, retests found lead again, and in 2018 the district shut off drinking water in every school.", pos: "tl" },
        ],
        cites: [11, 12],
        prompt: "Wide 16:9. A long Detroit school hallway with every drinking fountain wrapped in a plastic bag and taped shut, cases of bottled water stacked on a cart, students walking past. Muted blue, a single warm gold light at the end of the hall.",
      },
    ],
  },
  {
    label: "Part 4",
    chapter: "Second chances",
    panels: [
      {
        id: "e10",
        where: "detroit",
        size: "half",
        tag: "Detroit Animal Care · 2016",
        scene: "Open the door",
        art: null,
        alt: "A dog walks out of a shelter on a leash toward a waiting family.",
        captions: [
          { text: "The department also ran animal control. He raised officer pay, moved to a better building, doubled the budget and brought in rescue partners.", pos: "tl" },
        ],
        cites: [13, 14],
        prompt: "Landscape 4:3. A shelter door swings open onto a sunny Detroit sidewalk; a scruffy pit-bull mix trots out on a leash toward a family with two kids kneeling with open arms. Bright gold sunlight, Detroit blue sky.",
      },
      {
        id: "e11",
        where: "detroit",
        size: "half",
        type: "stat",
        tag: "2015 → 2016",
        big: "2,260 → 1,107",
        label: "animals euthanized",
        sub: "Live releases rose from about a quarter of animals to about 62%.",
        cites: [13, 14],
      },
    ],
  },
  {
    label: "Part 5",
    chapter: "Wayne County",
    intro: "In 2023 he went back into government, running health, human and veterans services for Michigan's biggest county.",
    panels: [
      {
        id: "e12",
        where: "detroit",
        size: "wide",
        splash: true,
        tag: "Wayne County · 2024",
        scene: "The envelope",
        art: null,
        alt: "A family at a kitchen table opens a letter; a pile of past-due bills shrinks.",
        captions: [
          { text: "Wayne County buys up residents' old medical debt for pennies on the dollar through a nonprofit, then cancels it. Families get a letter in the mail: it's gone.", pos: "tl" },
        ],
        bubbles: [
          { who: "El-Sayed", text: "Nobody takes on medical debt willingly. Illness or injury drove them to it.", pos: "right low" },
        ],
        cites: [15, 16],
        prompt: "Wide 16:9 splash. A Detroit kitchen table at night: a middle-aged Black couple opens an envelope together, relief on their faces, while a tall pile of red PAST DUE bills beside them shrinks and dissolves into floating paper confetti. Warm lamp gold, Detroit blue shadows.",
      },
      {
        id: "e13",
        where: "detroit",
        size: "third",
        type: "stat",
        tag: "Medical debt",
        big: "$57.4M",
        label: "of medical debt erased",
        sub: "For 83,291 residents, per Bridge Michigan's fact-check. The program's goal is $700 million.",
        cites: [17, 15],
      },
      {
        id: "e14",
        where: "detroit",
        size: "third",
        type: "stat",
        tag: "Overdose response",
        big: "100",
        label: "free naloxone vending machines",
        sub: "The biggest city or county naloxone buy in the country, with a machine in every one of the county's 45 cities and townships.",
        cites: [18],
      },
      {
        id: "e15",
        where: "detroit",
        size: "third",
        type: "stat",
        tag: "Since Sept 2024",
        big: "36,024",
        label: "naloxone kits handed out",
        sub: "Wayne County overdose deaths fell 42% in 2024. Deaths fell nationwide too, so the machines were one part of it.",
        cites: [18, 19],
      },
      {
        id: "e16",
        where: "detroit",
        size: "wide",
        tag: "Detroit · 2020–21",
        scene: "Keep the water on",
        art: null,
        alt: "Water running from a faucet on a Detroit porch, with an $18 bill on the step.",
        captions: [
          { text: "In 2020 he stands with Mayor Duggan to extend the city's pause on water shutoffs, then advises on a plan that ties water bills to income, as low as $18 a month.", pos: "tl" },
        ],
        cites: [20],
        prompt: "Wide 16:9. A Detroit front porch on a summer evening: a grandmother fills a glass from an outdoor spigot while kids play in a sprinkler, a water bill reading $18 held by a magnet to the door. Warm gold light, bright Detroit blue water.",
      },
    ],
  },
  {
    label: "Part 6",
    chapter: "Outspent",
    panels: [
      {
        id: "e17",
        where: "detroit",
        size: "two-thirds",
        tag: "Michigan · Summer 2026",
        scene: "Door by door",
        art: null,
        alt: "A volunteer with a clipboard at a front door, a wall of TV attack ads behind him.",
        captions: [
          { text: "The Senate primary becomes one of the most expensive ever. Outside groups backing his opponent outspend him 11 to 1.", pos: "tl" },
          { text: "His answer: volunteers, doors and small donors.", pos: "bl" },
        ],
        cites: [21, 22],
        prompt: "Wide 2:1. A small figure of a volunteer with a clipboard knocking on a front door of a Michigan house, while behind him a towering wall of glowing TV screens full of attack ads stretches eleven times his height into the night sky. David-and-Goliath composition, Detroit blue and harsh white TV glow.",
      },
      {
        id: "e18",
        where: "detroit",
        size: "third",
        type: "stat",
        tag: "FEC filings",
        big: "$14.5M",
        label: "raised, about 99% from individuals",
        sub: "No corporate PAC money. More itemized and small-dollar donors than his Republican opponent.",
        cites: [23, 24],
      },
      {
        id: "e19",
        where: "detroit",
        size: "wide",
        splash: true,
        tag: "The Majestic Theatre · Aug 4, 2026",
        scene: "Still standing",
        art: null,
        alt: "El-Sayed on stage at the Majestic Theatre in Detroit, arms raised.",
        captions: [
          { text: "He wins by 13,792 votes: 61% in Kent County, 59% in Ingham, and big margins with election-day voters in metro Detroit.", pos: "tl" },
        ],
        bubbles: [
          { who: "El-Sayed", text: "They outspent us $11 to $1. And yet we're still standing.", pos: "right high", shout: true },
        ],
        sfx: { text: "WON!", pos: "tr" },
        cites: [21, 25, 26],
        prompt: "Wide 16:9 splash. Inside Detroit's historic Majestic Theatre on primary night: an Egyptian-American man in a dark suit on stage with both fists raised, a roaring crowd with phone lights and union T-shirts, confetti falling, the theater's ornate marquee lights glowing. Explosive gold and Detroit blue.",
      },
      {
        id: "e20",
        where: "detroit",
        size: "half",
        tag: "August 2026",
        scene: "The party comes together",
        art: null,
        alt: "Former rivals and union members on stage together.",
        captions: [
          { text: "Haley Stevens concedes and offers her full support. Mallory McMorrow endorses. The UAW is joined by the Michigan AFL-CIO, over a million union members.", pos: "tl" },
        ],
        cites: [27, 28],
        prompt: "Landscape 4:3. A Michigan union hall stage: several politicians and union members in UAW and AFL-CIO jackets link raised hands in a row, an Egyptian-American candidate in the center, a huge American flag behind. Warm gold stage light, Detroit blue.",
      },
      {
        id: "e21",
        where: "detroit",
        size: "half",
        tag: "Nov 3, 2026",
        scene: "Round two",
        art: null,
        alt: "El-Sayed walking toward the Michigan Capitol at dawn.",
        captions: [
          { text: "Next: Republican Mike Rogers on November 3. Polls call it close, and Rogers' side is outspending him again.", pos: "tl" },
        ],
        cites: [29, 23],
        prompt: "Landscape 4:3. Dawn in Lansing: an Egyptian-American man in a black henley walks alone toward the lit Michigan State Capitol dome, long shadow ahead of him, a boxing-ring bell hanging in the sky like a moon. Cool Detroit blue with a gold sunrise.",
      },
    ],
  },
];

export const BACK = {
  label: "Receipts, checked",
  title: "Fact-check corner",
  intro: "His biggest claims, and the biggest attacks on him, checked against independent reporting.",
};

export const PLANKS = [
  { where: "detroit", status: "Checks out", who: "His claim", title: "Rebuilt Detroit's health department", cites: [1, 2], text: "It went from five city employees to about 220 in 18 months." },
  { where: "detroit", status: "Checks out", who: "His claim", title: "Fought the refinery and won", cites: [5, 6], text: "Marathon cut its permitted sulfur dioxide by 20% after community backlash he joined. New federal rules added pressure too." },
  { where: "detroit", status: "Overstated", who: "His claim", title: "\"Removed lead from Detroit's elementary schools\"", cites: [7, 11, 12], text: "His team tested the schools and exposed the lead. Later retests found it again, and in 2018 the district shut off drinking water in every school." },
  { where: "detroit", status: "Overstated", who: "His claim", title: "\"$700 million in medical debt erased\"", cites: [17], text: "Bridge Michigan counts $57.4 million erased for 83,291 people. $700 million is the program's goal." },
  { where: "detroit", status: "Attack debunked", who: "Attack on him", title: "\"A dog slaughterhouse\"", cites: [13, 14], text: "Fact-checkers found the attack cherry-picks years. On his watch euthanasia fell by half, from 2,260 to 1,107." },
  { where: "detroit", status: "Checks out", who: "His claim", title: "\"Outspent 11 to 1\"", cites: [21, 22], text: "Bridge Michigan confirms groups backing his primary opponent outspent him 11 to 1." },
  { where: "detroit", status: "Checks out", who: "His claim", title: "No corporate PAC money", cites: [23, 24], text: "About 99% of his money came from individuals, with no corporate PAC, party or loan money." },
];

export const SOURCES = [
  { n: 1, label: "STAT, Detroit's health director.", url: "https://www.statnews.com/2016/05/03/detroit-health-director/" },
  { n: 2, label: "Detroit News, Detroit health director to make bid for governor.", url: "https://www.detroitnews.com/story/news/local/detroit-city/2017/02/09/detroit-health-director-make-bid-governor/97690634/" },
  { n: 3, label: "WDET, free eye exams and glasses for DPSCD students.", url: "https://wdet.org/posts/2016/10/12/83985-new-program-provides-free-eye-exam-and-glasses-to-dpscd-students" },
  { n: 4, label: "Detroit News, children's blood lead levels spike.", url: "https://www.detroitnews.com/story/news/politics/2016/08/15/childrens-blood-lead-levels-spike/88814396/" },
  { n: 5, label: "Michigan Public, residents angry about Marathon's request to increase emissions.", url: "https://www.michiganpublic.org/environment-science/2016-01-26/detroit-residents-angry-about-marathon-refinerys-request-to-increase-emissions" },
  { n: 6, label: "Detroit News, Marathon to cut emissions after backlash.", url: "https://www.detroitnews.com/story/news/local/detroit-city/2016/03/28/marathon-cut-emissions-backlash/82365328/" },
  { n: 7, label: "Detroit News, elevated lead levels found in Detroit schools' water.", url: "https://www.detroitnews.com/story/news/local/detroit-city/2016/04/13/elevated-lead-levels-found-detroit-schools-water/83013420/" },
  { n: 8, label: "Detroit News, Detroit schools water contamination.", url: "https://www.detroitnews.com/story/news/local/detroit-city/2016/04/14/detroit-schools-water-contamination-lead-copper/83048856/" },
  { n: 9, label: "Detroit News, children's blood lead levels spike (2016 testing).", url: "https://www.detroitnews.com/story/news/politics/2016/08/15/childrens-blood-lead-levels-spike/88814396/" },
  { n: 10, label: "Michigan Public, Detroit demolitions linked to rising lead levels in children.", url: "https://www.michiganpublic.org/families-community/2017-11-14/detroit-demo-blitz-linked-to-rising-lead-levels-in-children" },
  { n: 11, label: "NPR, Detroit's school district shuts off drinking water.", url: "https://www.npr.org/2018/08/30/643247780/detroits-public-school-district-shuts-off-drinking-water-citing-lead-copper-risk" },
  { n: 12, label: "Washington Free Beacon, on his school lead claim.", url: "https://freebeacon.com/democrats/abdul-el-sayed-falsely-claims-he-removed-lead-from-the-water-in-detroit-elementary-schools-when-he-was-citys-health-director/" },
  { n: 13, label: "Bridge Michigan, fact-check: Detroit dogs and cats under El-Sayed.", url: "https://bridgemi.com/michigan-government/fact-check-what-happened-to-detroit-dogs-and-cats-under-abdul-el-sayed/" },
  { n: 14, label: "Snopes, the \"dog slaughterhouse\" claim.", url: "https://www.snopes.com/fact-check/el-sayed-dog-slaughterhouse-detroit/" },
  { n: 15, label: "Undue Medical Debt, Wayne County erases $27 million for 46,000 residents.", url: "https://unduemedicaldebt.org/press-release/wayne-county-announces-27-million-of-medical-debt-erased-for-over-46000-county-residents/" },
  { n: 16, label: "WXYZ, Wayne County erases nearly $42 million in medical debt.", url: "https://www.wxyz.com/news/region/wayne-county/wayne-county-erases-nearly-42-million-in-medical-debt-for-thousands-of-residents" },
  { n: 17, label: "Bridge Michigan, fact-check: El-Sayed overstates medical debt claim.", url: "https://bridgemi.com/michigan-government/fact-check-abdul-el-sayed-overstates-claim-he-erased-700m-in-medical-debt/" },
  { n: 18, label: "Wayne State Center for Behavioral Health and Justice, the naloxone vending machine program.", url: "https://behaviorhealthjustice.wayne.edu/news/data-drives-wayne-countys-groundbreaking-narcan-vending-machine-program-to-prevent-fatal-overdoses-61486" },
  { n: 19, label: "WDET, Wayne County sees drop in overdose deaths.", url: "https://wdet.org/2026/07/28/the-metro-wayne-county-finally-sees-drop-in-overdose-deaths-but-new-drugs-spark-concern/" },
  { n: 20, label: "Planet Detroit, El-Sayed on ending water shutoffs.", url: "https://planetdetroit.org/2021/11/duggan-water-exec-dr-abdul-el-sayed-detroit-focused-on-ending-shutoffs-but-affordability-needs-national-attention/" },
  { n: 21, label: "Bridge Michigan, how El-Sayed won Michigan.", url: "https://bridgemi.com/michigan-government/how-abdul-el-sayed-won-michigan-big-turnout-liberal-towns-walkup-votes/" },
  { n: 22, label: "Bridge Michigan, outside spending floods the Senate race.", url: "https://bridgemi.com/michigan-government/outside-spending-floods-michigans-us-senate-race-most-for-haley-stevens/" },
  { n: 23, label: "Detroit News, Senate race spending and donors.", url: "https://www.detroitnews.com/story/news/politics/2026/09/21/michigan-senate-spending-donors-abdul-el-sayed-mike-rogers/91824589007/" },
  { n: 24, label: "FEC, El-Sayed for Senate filings.", url: "https://www.fec.gov/data/candidate/S6MI00418/" },
  { n: 25, label: "NBC News, what El-Sayed's win shows.", url: "https://www.nbcnews.com/politics/2026-election/abdul-el-sayed-won-michigan-results-illustrate-challenges-ahead-rcna591052" },
  { n: 26, label: "The Nation, El-Sayed's primary night speech.", url: "https://www.thenation.com/article/politics/abdul-el-sayed-primary-results-speech/" },
  { n: 27, label: "Jewish Insider, Stevens concedes.", url: "https://jewishinsider.com/2026/08/el-sayed-victory-stevens-concedes-republicans-dangerous/" },
  { n: 28, label: "Michigan AFL-CIO, endorsement of El-Sayed.", url: "https://miaflcio.org/michigan-afl-cio-endorses-abdul-el-sayed-for-u-s-senate/" },
  { n: 29, label: "Washington Post, Michigan Senate poll.", url: "https://www.washingtonpost.com/politics/2026/09/17/michigan-senate-race-poll-finds-abdul-el-sayed-has-narrow-edge-over-mike-rogers/" },
];
