// Issue #2: Audacious. Zohran Mamdani's record.
//
// Same format as panels.js. Panels with `type: "stat"` are drawn by the page
// and need no art. Facts checked against the sources as of September 27, 2026.
// Where a result is disputed or unfinished, the caption says so.

export const PAGES = [
  {
    label: "Part 1",
    chapter: "The drivers",
    intro: "Before he ran the city, his biggest win was for the people who drive it.",
    panels: [
      {
        id: "m01",
        where: "queens",
        size: "wide",
        splash: true,
        tag: "New York · 2018",
        scene: "The medallion trap",
        art: null,
        alt: "A candlelight vigil for taxi drivers outside City Hall.",
        captions: [
          { text: "2018. Taxi medallions that once sold for up to a million dollars have crashed in value. The drivers who borrowed to buy them are drowning.", pos: "tl" },
          { text: "At least eight New York drivers take their own lives that year.", pos: "bl" },
        ],
        cites: [1, 2],
        prompt: "Wide 16:9 splash. A quiet candlelight vigil at night outside New York City Hall: immigrant taxi drivers of many backgrounds holding candles and framed photos of lost colleagues, yellow cabs parked in a line with hazard lights blinking. Somber, respectful, no depiction of violence. Deep blue night, warm candle gold, a soft magenta rim light.",
      },
      {
        id: "m02",
        where: "queens",
        size: "two-thirds",
        tag: "City Hall · Oct 2021",
        scene: "Fifteen days",
        art: null,
        alt: "Mamdani and drivers on hunger strike on the sidewalk outside City Hall.",
        captions: [
          { text: "Richard Chow lost his brother Kenny in 2018. In 2021 he sits on the sidewalk outside City Hall on hunger strike, next to a young assemblyman from Astoria.", pos: "tl" },
        ],
        bubbles: [{ who: "Richard Chow", text: "We're going to save 6,000 medallion owners. No more suicides.", pos: "right low" }],
        cites: [3, 1],
        prompt: "Wide 2:1. Night, the sidewalk outside City Hall: an older Burmese-American taxi driver in a windbreaker and a thin young South Asian assemblyman sit side by side on folding chairs under a tarp, blankets on their knees, water bottles at their feet, yellow cabs behind them. Exhausted, determined, rain on the tarp.",
      },
      {
        id: "m03",
        where: "queens",
        size: "third",
        type: "stat",
        tag: "Debt relief",
        big: "$471M",
        label: "in medallion debt wiped out",
        sub: "for more than 2,000 owners, under the relief program the hunger strike won.",
        cites: [5, 6],
      },
      {
        id: "m04",
        where: "queens",
        size: "wide",
        tag: "Jan 1, 2026",
        scene: "Start the meter",
        art: null,
        alt: "Richard Chow's yellow cab pulls up to City Hall with the mayor-elect inside.",
        captions: [
          { text: "Four years later, on inauguration day, Richard Chow washes his cab, dusts the seats and drives the new mayor and his wife to City Hall.", pos: "tl" },
          { text: "The mayor reminds him to start the meter.", pos: "br" },
        ],
        cites: [3, 4],
        prompt: "Wide 16:9. New Year's Day morning, a freshly washed yellow NYC taxi pulls up to the steps of City Hall, the driver (an older Burmese-American man) smiling proudly behind the wheel, a young South Asian man in a dark coat and a young Syrian-American woman in the back seat, the taxi's roof light glowing. Crisp winter light, confetti in the air, gold and cyan.",
      },
    ],
  },
  {
    label: "Part 2",
    chapter: "Albany",
    intro: "Three bills with his name on them became law, all minor. His bigger Assembly wins came from organizing and budget fights.",
    panels: [
      {
        id: "m05",
        where: "queens",
        size: "half",
        tag: "Astoria · Oct 2021",
        scene: "No new smokestack",
        art: null,
        alt: "The Astoria waterfront, smokestacks fading into wind turbines.",
        captions: [
          { text: "A power company wants a new gas plant on the Astoria waterfront. Mamdani helps lead the fight against it.", pos: "tl" },
          { text: "October 2021: the state denies the permit, saying the plant isn't needed and clashes with the state's climate law.", pos: "bl" },
        ],
        cites: [7, 8],
        prompt: "Landscape 4:3. The Astoria, Queens waterfront at dusk: old red-and-white smokestacks dissolving into drifting pixels on the left, turning into white offshore wind turbines on the horizon on the right. Neighbors with protest signs (no readable words) cheer on a pier in the foreground. Gold sunset, cyan sky.",
      },
      {
        id: "m06",
        where: "queens",
        size: "half",
        tag: "Five routes · 2023–24",
        scene: "Fare-free",
        art: null,
        alt: "Riders boarding a fare-free bus through both doors.",
        captions: [
          { text: "He fights for a $15 million fare-free bus pilot in the state budget. For a year, one route in each borough runs free.", pos: "tl" },
        ],
        cites: [9, 10],
        prompt: "Landscape 4:3. A Bronx bus stop in the morning: riders of every age, a grandmother with a cart, students, a nurse in scrubs, all board through the front and back doors at once; the fare box is covered. The bus is noticeably full. Warm gold light, cyan sky.",
      },
      {
        id: "m07",
        where: "queens",
        size: "third",
        type: "stat",
        tag: "MTA's own report",
        big: "+30%",
        label: "weekday riders on the free routes",
        sub: "and +38% on weekends.",
        cites: [9],
      },
      {
        id: "m08",
        where: "queens",
        size: "third",
        type: "stat",
        tag: "Safer for drivers",
        big: "−32%",
        label: "assaults on bus operators on the free routes",
        sub: "Assaults fell 15% systemwide too, so part of that drop is a citywide trend.",
        cites: [9, 11],
      },
      {
        id: "m09",
        where: "queens",
        size: "third",
        type: "stat",
        tag: "Why they rode",
        big: "23%",
        label: "of riders said they took the trip because it was free",
        sub: "Albany let the pilot end in August 2024.",
        cites: [9, 11],
      },
    ],
  },
  {
    label: "Part 3",
    chapter: "Day one",
    panels: [
      {
        id: "m10",
        where: "queens",
        size: "two-thirds",
        tag: "City Hall · Jan 1, 2026",
        scene: "Five pens",
        art: null,
        alt: "Mamdani signing executive orders at a desk in City Hall.",
        captions: [
          { text: "On his first day he signs five executive orders.", pos: "tl" },
          { text: "One revives the Mayor's Office to Protect Tenants. Another orders a hunt for city land to build at least 25,000 homes.", pos: "bl" },
        ],
        cites: [13, 14],
        prompt: "Wide 2:1. A grand wood-paneled City Hall office at night, a young South Asian mayor in shirtsleeves signing a stack of documents with a row of pens, advisors leaning in, a window behind him with the Brooklyn Bridge lit up. Warm lamp gold, cool blue window light.",
      },
      {
        id: "m11",
        where: "queens",
        size: "third",
        type: "stat",
        tag: "City land",
        big: "100+",
        label: "city-owned sites mapped for new homes",
        sub: "Room for more than 50,000, per the city's LIFT tracker. The first award: 131 affordable homes on an NYPD parking lot.",
        cites: [14, 15],
      },
      {
        id: "m12",
        where: "queens",
        size: "wide",
        tag: "Bankruptcy court · January",
        scene: "The Pinnacle tenants",
        art: null,
        alt: "Tenants holding photos of mold and broken ceilings in a courtroom.",
        captions: [
          { text: "Day one, the city also steps into the bankruptcy of Pinnacle Group, landlord of about 5,100 rent-stabilized apartments with thousands of open violations.", pos: "tl" },
          { text: "The sale that follows comes with a promised $30 million in repairs. Critics note the promise isn't in escrow; tenants are watching.", pos: "br" },
        ],
        cites: [16, 17],
        prompt: "Wide 16:9. A packed courtroom: working-class tenants of many backgrounds stand in the gallery holding up phone photos and printouts of moldy walls, cracked ceilings and broken radiators; a lawyer for the city stands at the podium. Dramatic side light, gold and cyan.",
      },
    ],
  },
  {
    label: "Part 4",
    chapter: "The freeze",
    panels: [
      {
        id: "m13",
        where: "queens",
        size: "wide",
        splash: true,
        tag: "El Museo del Barrio · June 25, 2026",
        scene: "The vote",
        art: null,
        alt: "Tenants on their feet cheering in a museum auditorium as the vote is read.",
        captions: [
          { text: "June 25, 2026. The Rent Guidelines Board meets at El Museo del Barrio in East Harlem. Tenants chant in four languages.", pos: "tl" },
          { text: "The vote: 7 to 1. Zero percent on one-year leases, and the first freeze on two-year leases in the board's history.", pos: "bl" },
        ],
        bubbles: [{ who: "Mamdani", text: "This is the relief that working people across our city deserve.", pos: "right high" }],
        sfx: { text: "FROZEN!", pos: "tr" },
        cites: [18, 19, 22],
        prompt: "Wide 16:9 splash. A packed museum auditorium in East Harlem, tenants of every age and background on their feet cheering, homemade signs (no readable text), a board of officials at a long table on stage. Frost and ice crystals burst across the frame. Cyan ice, gold light, magenta accents.",
      },
      {
        id: "m14",
        where: "queens",
        size: "third",
        type: "stat",
        tag: "Who it covers",
        big: "~1M",
        label: "rent-stabilized apartments",
        sub: "Home to about 2 million New Yorkers.",
        cites: [18, 20],
      },
      {
        id: "m15",
        where: "queens",
        size: "third",
        tag: "Bed-Stuy",
        scene: "Darryl Randall",
        art: null,
        alt: "A tenant in his kitchen, shoulders relaxed, reading the news on his phone.",
        bubbles: [{ who: "Darryl Randall, 57", text: "There's a lot of stress and weight taken off my shoulders.", pos: "center low" }],
        cites: [20],
        prompt: "Square 1:1. A Black man in his late fifties in a small Bed-Stuy kitchen, reading the news on his phone and exhaling in relief, a stack of bills on the table pushed aside, morning light through the window. Warm gold, soft cyan.",
      },
      {
        id: "m16",
        where: "queens",
        size: "third",
        tag: "The other side",
        scene: "Landlords push back",
        art: null,
        alt: "An empty chair at the board's table.",
        captions: [
          { text: "Landlords call the vote outrageous. A landlord-side board member resigns hours before it. Lawsuits are expected.", pos: "tl" },
        ],
        cites: [21, 19],
        prompt: "Square 1:1. An empty chair pushed back from a long official table, a nameplate face down, papers scattered. Dramatic single spotlight, cool blue and gold.",
      },
    ],
  },
  {
    label: "Part 5",
    chapter: "Kids first",
    panels: [
      {
        id: "m17",
        where: "queens",
        size: "two-thirds",
        tag: "Washington Heights · Sept 2026",
        scene: "2-K opens",
        art: null,
        alt: "A parent hands a toddler to a teacher at the door of a bright classroom.",
        captions: [
          { text: "Free child care for two-year-olds: about 2,000 seats in four neighborhoods, most open ten hours a day, year-round, regardless of income.", pos: "tl" },
          { text: "More than 5,700 families apply.", pos: "bl" },
        ],
        bubbles: [{ who: "Suz Kroeber, parent", text: "We couldn't get a seat, and we had to literally pay the price for it.", pos: "right low" }],
        cites: [23, 24, 25, 26],
        prompt: "Wide 2:1. 8 a.m. at the door of a bright Washington Heights classroom: a young Dominican-American mother hands her two-year-old to a smiling teacher, other toddlers painting inside, a price tag reading nothing floats away out the window. Warm morning gold, soft pink.",
      },
      {
        id: "m18",
        where: "queens",
        size: "third",
        type: "stat",
        tag: "What a seat is worth",
        big: "$26K",
        label: "a year, per child",
        sub: "The city's estimate of what each free 2-K seat saves a family.",
        cites: [23],
      },
      {
        id: "m19",
        where: "queens",
        size: "third",
        type: "stat",
        tag: "No more copays",
        big: "22,000",
        label: "low-income families now pay $0 for child care",
        sub: "Weekly fees of up to $15 are gone, starting September 2026.",
        cites: [28],
      },
      {
        id: "m20",
        where: "queens",
        size: "third",
        type: "stat",
        tag: "3-K",
        big: "+2,000",
        label: "new 3-K seats in all five boroughs",
        sub: "Opening this fall.",
        cites: [27],
      },
      {
        id: "m21",
        where: "queens",
        size: "third",
        type: "stat",
        tag: "FY27 budget",
        big: "$1,000",
        label: "in a college account for every public-school kindergartner",
        sub: "Up from $100. It can pay for trade school, community college or a four-year degree.",
        cites: [29, 30],
      },
    ],
  },
  {
    label: "Part 6",
    chapter: "Paid in full",
    panels: [
      {
        id: "m22",
        where: "queens",
        size: "wide",
        splash: true,
        tag: "Sept 22, 2026",
        scene: "The DoorDash settlement",
        art: null,
        alt: "Delivery workers on e-bikes in the rain, phones lighting up with back pay.",
        captions: [
          { text: "Rosendo Tacam, a Queens delivery worker, went an entire week without being paid.", pos: "tl" },
          { text: "September 2026: the city wins $131.5 million from DoorDash, the largest worker settlement in city history. Payments go out automatically to about 260,000 workers.", pos: "bl" },
        ],
        bubbles: [
          { who: "Mamdani", text: "Not tomorrow, not after a lawsuit, but on time and in full.", pos: "right high" },
        ],
        sfx: { text: "PAID!", pos: "tr" },
        cites: [33, 34, 35],
        prompt: "Wide 16:9 splash. A rainy New York avenue at night, a line of delivery workers on e-bikes with insulated bags, their phone screens lighting up their faces as notifications arrive, one Guatemalan-American rider in front grinning and raising a fist. Neon storefront reflections, gold coins sparkling in the rain. Cyan and gold.",
      },
      {
        id: "m23",
        where: "queens",
        size: "half",
        type: "stat",
        tag: "Uber Eats · January",
        big: "10,000",
        label: "couriers eligible to get their accounts back",
        sub: "after being wrongfully deactivated, plus $5 million in restitution and penalties from three apps.",
        cites: [36],
      },
      {
        id: "m24",
        where: "queens",
        size: "half",
        type: "stat",
        tag: "Half-price transit",
        big: "+340,000",
        label: "New Yorkers newly eligible for Fair Fares",
        sub: "The City Council pushed the expansion into the budget, and the mayor signed on.",
        cites: [31, 32],
      },
    ],
  },
  {
    label: "Part 7",
    chapter: "Taking on the powerful",
    panels: [
      {
        id: "m25",
        where: "queens",
        size: "third",
        type: "stat",
        tag: "Pied-à-terre tax",
        big: "~$500M",
        label: "a year from a new tax on luxury second homes",
        sub: "New York's first. He didn't get the millionaire's tax he campaigned on.",
        cites: [37, 38, 39],
      },
      {
        id: "m26",
        where: "queens",
        size: "two-thirds",
        tag: "Sept 8, 2026",
        scene: "The 9/11 files",
        art: null,
        alt: "Firefighters reading stacks of released documents.",
        captions: [
          { text: "25 years after 9/11, he releases more than 170,000 pages of city records and settles two lawsuits over them.", pos: "tl" },
          { text: "The files show officials worried about Ground Zero's air while telling the public it was safe.", pos: "bl" },
        ],
        cites: [40, 41],
        prompt: "Wide 2:1. A union hall at night, retired FDNY firefighters and their families gathered around long tables piled with released documents and laptops, one older firefighter holding up a page, the Tribute in Light beams visible through a window. Somber, gold lamp light, blue night.",
      },
      {
        id: "m27",
        where: "queens",
        size: "wide",
        tag: "Sept 2026",
        scene: "New York leads the suit",
        art: null,
        alt: "City lawyers filing a lawsuit on courthouse steps with other cities' officials.",
        captions: [
          { text: "New York City leads a coalition of cities suing to block a federal rule that could deny green cards to immigrants who use Medicaid, food stamps or housing aid.", pos: "tl" },
          { text: "The case is still in court.", pos: "br" },
        ],
        cites: [42],
        prompt: "Wide 16:9. Federal courthouse steps in daylight, a diverse group of city lawyers and officials from several cities walking up together carrying binders, immigrant families watching from the sidewalk holding hands. Bright gold sun, cyan sky, heroic low angle.",
      },
    ],
  },
];

export const BACK = {
  label: "Promise tracker",
  title: "What he said he'd do",
  intro: "His campaign promises, and where each one stands as of September 27, 2026.",
};

export const PLANKS = [
  { where: "queens", status: "Done", who: "Rent", title: "Freeze the rent", cites: [18, 48], text: "0% on one- and two-year leases for about a million rent-stabilized apartments, starting October 1, 2026. Landlords are expected to sue." },
  { where: "queens", status: "In progress", who: "Child care", title: "Universal child care", cites: [23, 24, 28, 48], text: "2,000 free 2-K seats open this fall, copays are gone for 22,000 families, and 2,000 more 3-K seats are opening. The promise is care for every child from six weeks to five years old; the plan is about 12,000 2-K seats next year." },
  { where: "queens", status: "In progress", who: "Buses", title: "Fast buses", cites: [43], text: "A July 2026 plan with the state targets 50 corridors and buses 20% faster, with all-door boarding in 2027. Most of it hasn't been built yet." },
  { where: "queens", status: "Not yet", who: "Buses", title: "Free buses", cites: [44, 39], text: "He conceded in April that citywide free buses won't happen this year, and the state budget didn't fund a new pilot." },
  { where: "queens", status: "In progress", who: "Groceries", title: "City-owned grocery stores", cites: [47], text: "The first sites are chosen: La Marqueta in East Harlem and The Peninsula in Hunts Point. None is open yet; reports put the first opening between 2027 and 2029." },
  { where: "queens", status: "In progress", who: "Housing", title: "Build on city land", cites: [14, 15], text: "More than 100 city sites mapped for over 50,000 homes. The first award, 131 affordable homes in the East Village, is designated but not built." },
  { where: "queens", status: "In progress", who: "Safety", title: "Department of Community Safety", cites: [45, 46], text: "He created an Office of Community Safety with $260 million, short of the $1.1 billion department he pledged. No results have been published yet." },
  { where: "queens", status: "Partly", who: "Taxes", title: "Tax the top", cites: [37, 39], text: "Albany passed a new pied-à-terre tax on luxury second homes. It rejected his 2% millionaire's tax and corporate tax hike." },
  { where: "queens", status: "Done", who: "Workers", title: "Make companies pay what they owe", cites: [33, 36], text: "Record settlements from DoorDash ($131.5 million) and Uber Eats and two other apps (more than $5 million), with payments sent automatically." },
];

export const SOURCES = [
  { n: 1, label: "The Nation, the taxi drivers' strike.", url: "https://www.thenation.com/article/society/taxi-driver-strike/" },
  { n: 2, label: "Boston Globe, surge in suicides of taxi drivers shakes New York.", url: "https://www.bostonglobe.com/business/2018/12/02/surge-suicides-taxi-drivers-shakes-new-york/VDYZqfiqmqkdLs27QBRlOJ/story.html" },
  { n: 3, label: "New York Times, \"Mayor Mamdani and the Taxi Driver\" (reprint).", url: "https://www.aol.com/articles/mamdani-went-hunger-strike-cab-000809971.html" },
  { n: 4, label: "Irish Times, how a taxi driver and Mayor Mamdani united for change.", url: "https://www.irishtimes.com/world/us/2026/02/04/how-a-new-york-taxi-driver-and-mayor-zohran-mamdani-united-for-change/" },
  { n: 5, label: "City Council hearing, TLC testimony on the medallion relief program, Feb 10, 2025.", url: "https://citymeetings.nyc/meetings/new-york-city-council/2025-02-10-1000-am-committee-on-transportation-and-infrastructure/chapter/overview-and-impact-of-the-taxi-medallion-owner-relief-program/" },
  { n: 6, label: "NYC Mayor's Office, $350 million in medallion debt relief delivered.", url: "https://www.nyc.gov/mayors-office/news/2023/01/mayor-adams-tlc-senator-schumer-celebrate-350-million-debt-relief-delivered-taxi-medallion" },
  { n: 7, label: "NY Assembly, Mamdani on the Astoria peaker plant.", url: "https://nyassembly.gov/mem/Zohran-K-Mamdani/story/104015" },
  { n: 8, label: "City Limits, state rejects permit for Astoria power plant.", url: "https://citylimits.org/new-york-state-rejects-permit-for-proposed-astoria-power-plant/" },
  { n: 9, label: "MTA, fare-free bus pilot one-year evaluation.", url: "https://www.mta.info/document/177466" },
  { n: 10, label: "The Nation, New York City's free bus experiment.", url: "https://www.thenation.com/article/society/new-york-city-bus-free-fare/" },
  { n: 11, label: "amNY, MTA free bus pilot ends.", url: "https://www.amny.com/nyc-transit/mta-free-bus-pilot-ending-ridership/" },
  { n: 12, label: "CBS New York, swearing-in at the old City Hall station.", url: "https://www.cbsnews.com/newyork/news/zohran-mamdani-swearing-in-old-city-hall-station/" },
  { n: 13, label: "NYC Mayor's Office, executive order reviving the Mayor's Office to Protect Tenants.", url: "https://www.nyc.gov/mayors-office/news/2026/01/mayor-mamdani-signs-eo-to-revitalize-mayor-s-office-to-protect-t" },
  { n: 14, label: "NYC Mayor's Office, LIFT tracker for affordable housing on city land.", url: "https://www.nyc.gov/mayors-office/news/2026/07/mayor-mamdani-launches-lift-tracker-to-build-affordable-housing-" },
  { n: 15, label: "Gothamist, NYPD parking lot to become affordable housing.", url: "https://gothamist.com/news/mamdani-wants-to-turn-an-underutilized-nypd-parking-lot-into-affordable-housing" },
  { n: 16, label: "NYC Mayor's Office, cracking down on bad landlords.", url: "https://www.nyc.gov/mayors-office/news/2026/04/mayor-mamdani-takes-on-the-housing-crisis--cracks-down-on-bad-la" },
  { n: 17, label: "Crain's New York, editorial on the Pinnacle bankruptcy decision.", url: "https://www.crainsnewyork.com/editorials/editorial-pinnacle-group-bankruptcy-decision-moral-stand-meets-market-reality" },
  { n: 18, label: "Gothamist, Rent Guidelines Board approves two-year rent freeze.", url: "https://gothamist.com/news/nyc-rent-guidelines-board-approves-2-year-rent-freeze-fulfilling-mamdani-campaign-pledge" },
  { n: 19, label: "amNY, Rent Guidelines Board approves rent freeze.", url: "https://www.amny.com/housing/rent-guidelines-board-approves-rent-freeze/" },
  { n: 20, label: "NY1, tenant and landlord reaction to the freeze.", url: "https://ny1.com/nyc/all-boroughs/news/2026/06/26/tenant-landlord-reaction-nyc-rent-guidelines-board-freeze-vote" },
  { n: 21, label: "amNY, owner representative quits before the final vote.", url: "https://www.amny.com/news/rent-board-owner-rep-quits-before-final-vote/" },
  { n: 22, label: "NYC Mayor's Office, statement on the Rent Guidelines Board vote.", url: "https://www.nyc.gov/mayors-office/news/2026/06/mayor-mamdani-s-statement-on-the-rent-guidelines-board-s-final-v" },
  { n: 23, label: "NYC Mayor's Office, first four 2-K communities.", url: "https://www.nyc.gov/mayors-office/news/2026/03/mayor-mamdani-and-governor-hochul-announce-first-four-communitie" },
  { n: 24, label: "Governor's Office, 2-K offers to more than 2,000 children.", url: "https://www.governor.ny.gov/news/governor-hochul-and-mayor-mamdani-extend-2-k-offers-more-2000-children" },
  { n: 25, label: "Chalkbeat, 2-K will run 10 hours a day, year-round.", url: "https://www.chalkbeat.org/newyork/2026/04/09/2k-will-run-10-hours-a-day-year-round-mamdani-says/" },
  { n: 26, label: "The City Reporter, 2-K applications and offers.", url: "https://www.thecityreporter.nyc/2026/08/04/nyc-childcare-2k-mamdani-hochul-applications-offers/" },
  { n: 27, label: "amNY, new 3-K seats in all boroughs.", url: "https://www.amny.com/education/nyc-3-k-child-care-seats-all-boroughs/" },
  { n: 28, label: "Gothamist, child care made free for 22,000 families.", url: "https://gothamist.com/news/mamdani-makes-childcare-free-for-22k-nyc-families" },
  { n: 29, label: "Chalkbeat, budget gives kindergartners $1,000 for college.", url: "https://www.chalkbeat.org/newyork/2026/06/30/nyc-budget-gives-kindergartners-1000-for-college-restores-school-programs/" },
  { n: 30, label: "NYC Council, FY27 budget agreement.", url: "https://council.nyc.gov/press/2026/06/30/3151/" },
  { n: 31, label: "amNY, budget expands Fair Fares.", url: "https://www.amny.com/news/nyc-budget-fair-fares-expands-2026/" },
  { n: 32, label: "Streetsblog, Mamdani and the Council agree to expand Fair Fares.", url: "https://nyc.streetsblog.org/2026/06/30/mamdani-and-city-council-agree-to-expand-fair-fares-half-priced-transit-program" },
  { n: 33, label: "NYC Department of Consumer and Worker Protection, record $131.5 million from DoorDash.", url: "https://www.nyc.gov/site/dca/news/065-26/mayor-mamdani-wins-record-131-5-million-doordash-delivery-workers" },
  { n: 34, label: "Gothamist, DoorDash to pay $131.5 million.", url: "https://gothamist.com/news/doordash-to-pay-1315-million-to-delivery-workers-admitting-it-screwed-up" },
  { n: 35, label: "Documented, the DoorDash settlement and delivery workers.", url: "https://documentedny.com/2026/09/22/mamdani-delivery-workers-doordash-labor-settlement/" },
  { n: 36, label: "NYC Mayor's Office, $5 million settlement and reinstatement of couriers.", url: "https://www.nyc.gov/mayors-office/news/2026/01/mayor-mamdani-announces--5-million-settlement--reinstatement-of-" },
  { n: 37, label: "NYC Mayor's Office, the state's first pied-à-terre tax.", url: "https://www.nyc.gov/mayors-office/news/2026/04/mayor-mamdani--governor-hochul-announce-state-s-first-pied-a-ter" },
  { n: 38, label: "Gothamist, how Hochul and Mamdani compromised on taxing the rich.", url: "https://gothamist.com/news/how-hochul-and-mamdani-forged-a-compromise-over-taxing-the-rich" },
  { n: 39, label: "City & State, what Mamdani got and didn't get in Albany.", url: "https://www.cityandstateny.com/policy/2026/06/what-mamdani-got-and-didnt-get-albany-year/414015/" },
  { n: 40, label: "TIME, Mamdani to release 9/11-related documents.", url: "https://time.com/article/2026/09/08/mamdani-to-release-9-11-related-documents/" },
  { n: 41, label: "ABC7, FDNY unions on the released 9/11 air records.", url: "https://abc7ny.com/post/fdny-unions-demand-answers-newly-released-911-toxic-air-records/19809504/" },
  { n: 42, label: "Axios, cities sue over the public charge rule.", url: "https://www.axios.com/2026/09/14/trump-immigration-benefits-lawsuit-mamdani-nyc" },
  { n: 43, label: "Streetsblog, the Mamdani-Hochul bus plan.", url: "https://nyc.streetsblog.org/2026/07/08/the-mamdani-hochul-bus-plan-priority-corridors-bus-rapid-transit-lane-enforcement-and-finally-all-door-boarding" },
  { n: 44, label: "Washington Times, free bus pledge won't be fulfilled this year.", url: "https://www.washingtontimes.com/news/2026/apr/9/zohran-mamdani-concedes-free-bus-pledge-wont-fulfilled-year/" },
  { n: 45, label: "THE CITY, public safety and mental health calls.", url: "https://www.thecity.nyc/2026/03/19/public-safety-mental-health-calls-nypd-mamdani/" },
  { n: 46, label: "City & State, three big questions about the Office of Community Safety.", url: "https://www.cityandstateny.com/policy/2026/03/3-big-questions-about-mamdanis-new-office-community-safety/412261/" },
  { n: 47, label: "NY1, first city-owned grocery store site in East Harlem.", url: "https://ny1.com/nyc/manhattan/news/2026/04/13/zohran-mamdani-city-owned-grocery-store-east-harlem" },
  { n: 48, label: "Zohran for NYC, platform.", url: "https://zohranfornyc.com/" },
];
