// Two Roads to the Capitol: the comic script.
//
// Each panel's `art` is a file name in art/story/. While it is null the page
// draws a flat placeholder. `prompt` is the Makko art prompt for that panel;
// it is not shown on the page. `cites` are numbers in SOURCES.
//
// Sizes on a 6-column grid: wide = 6, two-thirds = 4, half = 3, third = 2.
// `tall` spans two rows. Every row has to add up to 6.
//
// Facts were checked against the sources as of September 27, 2026.

export const STYLE =
  "Bold American comic-book illustration, heavy black ink outlines, halftone dot shading, " +
  "rain-slick night lighting with neon magenta, cyan and gold accents, same painted-comic style " +
  "as the Capitol Crashers fighter-select screen. No text, no lettering, no speech bubbles.";

export const PAGES = [
  {
    label: "Part 1",
    chapter: "Two beginnings",
    panels: [
      {
        id: "p01",
        where: "queens",
        size: "half",
        tall: true,
        tag: "Kampala · 1991",
        scene: "Kampala, Uganda",
        art: "p01.webp",
        alt: "A newborn in Kampala, held by his mother, a filmmaker, and his father, a scholar.",
        captions: [
          { text: "October 18, 1991. Kampala, Uganda. Zohran Kwame Mamdani is born, his middle name a tribute to Kwame Nkrumah.", pos: "tl" },
          { text: "His mother is filmmaker Mira Nair. His father is Mahmood Mamdani, a scholar of colonialism.", pos: "bl" },
        ],
        cites: [1, 2],
        prompt: "Warm golden-hour Kampala hillside with red-earth roads and jacaranda trees. A young South Asian woman filmmaker with long dark wavy hair and a middle-aged Ugandan-Indian scholar in his mid-forties cradle a newborn wrapped in a patterned cloth. The scholar has round glasses, receding salt-and-pepper hair, a thin scholarly face, and no full beard. They are parents, not the young bearded fighters. Loving, hopeful. No lettering.",
      },
      {
        id: "p02",
        where: "detroit",
        size: "half",
        tag: "Southeast Michigan · 1984",
        scene: "Detroit, 1984",
        art: "p02.webp",
        alt: "An Egyptian engineer walks toward Wayne State University in Detroit.",
        captions: [
          { text: "October 31, 1984. Southeast Michigan. Abdulrahman \"Abdul\" El-Sayed is born.", pos: "tl" },
          { text: "His father came from Alexandria, Egypt, in 1979 to earn an engineering Ph.D. at Wayne State.", pos: "bl" },
        ],
        cites: [3, 4],
        prompt: "Early-1980s autumn campus at dusk. A young Egyptian engineer in his late twenties, short dark hair, thin mustache only, no full beard, brown corduroy jacket, stack of engineering textbooks, brick university buildings, Detroit skyline, faded Mediterranean lighthouse in the clouds. Not the bearded fighter. No readable text.",
      },
      {
        id: "p03",
        where: "detroit",
        size: "half",
        tag: "Bloomfield Hills",
        scene: "Three-sport captain",
        art: "p03.webp",
        alt: "A teenage El-Sayed in lacrosse gear under stadium lights.",
        captions: [{ text: "At Andover High he captains three teams at once: football, wrestling and lacrosse.", pos: "tl" }],
        sfx: { text: "CRACK!" },
        cites: [5],
        prompt: "Landscape 4:3. A determined Egyptian-American high-school athlete in a lacrosse helmet mid-shot, stick whipping forward, under Friday-night stadium lights in suburban Michigan. Dynamic action lines, sparks of neon cyan on the ball. Football and wrestling gear visible on a bench in the background.",
      },
      {
        id: "p04",
        where: "queens",
        size: "two-thirds",
        tag: "Cape Town → New York",
        scene: "A cricket bat in the Bronx",
        art: "p04.webp",
        alt: "A teenage Mamdani swings a cricket bat on a Bronx field, the city skyline behind him.",
        captions: [
          { text: "At five, his family moves to Cape Town. At seven, New York City.", pos: "tl" },
          { text: "At Bronx Science he co-founds the school's first cricket team.", pos: "bl" },
        ],
        sfx: { text: "THWACK!" },
        cites: [1, 2],
        prompt: "Skinny teenage South Asian boy on a patchy Bronx cricket field in white cricket kit, swinging a bat, red ball exploding off. Younger version of the adult with a full dark beard and thick styled dark hair: less beard, still dark hair with volume, not a professional cricket star. Split background Table Mountain and New York skyline. No readable text.",
      },
      {
        id: "p05",
        where: "detroit",
        size: "third",
        tag: "Ann Arbor · 2007",
        scene: "Commencement",
        art: "p05.webp",
        alt: "El-Sayed at a podium in a graduation gown.",
        captions: [{ text: "University of Michigan, class of 2007. He gives the student commencement speech.", pos: "tl" }],
        bubbles: [{ who: "El-Sayed", text: "The person who leaves here today is better than the one who came.", pos: "center low" }],
        cites: [5],
        prompt: "Square 1:1. A young Egyptian-American graduate in a black gown and maize-and-blue stole speaks at a podium, huge stadium crowd behind him in the rain of confetti. Low heroic angle, gold and blue light.",
      },
    ],
  },
  {
    label: "Part 2",
    chapter: "The training arc",
    panels: [
      {
        id: "p06",
        where: "detroit",
        size: "wide",
        tag: "Oxford · New York",
        scene: "Rhodes Scholar, doctor, professor",
        art: "p06.webp",
        alt: "A montage: Oxford spires, a Columbia white coat, an epidemiology lecture hall.",
        captions: [
          { text: "Rhodes Scholar. A doctorate in population health at Oxford. An M.D. from Columbia.", pos: "tl" },
          { text: "Then a professor of epidemiology at Columbia, studying how poverty makes people sick.", pos: "br" },
        ],
        cites: [5, 6, 7],
        prompt: "Wide 16:9 montage in three overlapping beats, left to right: the spires of Oxford at dusk with a young man in an academic gown; the same man pulling on a white doctor's coat in a New York hospital corridor; the same man at a chalkboard covered in charts and maps of a city, lecturing. One continuous figure, gold-to-cyan lighting gradient.",
      },
      {
        id: "p07",
        where: "queens",
        size: "half",
        tag: "Maine → Queens",
        scene: "Mr. Cardamom",
        art: "p07.webp",
        alt: "Mamdani on a Jackson Heights street with his grandmother in a music video.",
        captions: [
          { text: "Bowdoin College, Africana Studies, 2014. Then a detour: rapping as \"Mr. Cardamom.\"", pos: "tl" },
          { text: "His 2019 video \"Nani\" stars Madhur Jaffrey as his grandmother.", pos: "bl" },
        ],
        cites: [2, 8],
        prompt: "Landscape 4:3. A young South Asian man in a bright tracksuit raps on a busy Jackson Heights, Queens street under the elevated 7 train, beside a regal elderly Indian grandmother in a sari who is clearly the star. Halal cart steam, colorful shop signs (no readable words), playful magenta and gold lighting.",
      },
      {
        id: "p08",
        where: "queens",
        size: "half",
        tag: "Queens",
        scene: "The kitchen table",
        art: "p08.webp",
        alt: "Mamdani at a family's kitchen table going over foreclosure papers.",
        captions: [
          { text: "He becomes a housing counselor at Chhaya CDC in Queens, helping homeowners fight foreclosure.", pos: "tl" },
          { text: "That job is why he runs for office.", pos: "br" },
        ],
        cites: [9, 10],
        prompt: "Night in a small Queens kitchen. A young South Asian housing counselor: full dark beard, thick styled dark hair, light blue shirt, leaning over foreclosure papers. Across from him an anxious older immigrant couple who do not look like him: a gray-haired father and a mother, different faces. Warm lamp, cold blue window. He is the only young bearded man. No second politician. No short-cropped hair. No henley. No stethoscope. No lettering.",
      },
    ],
  },
  {
    label: "Part 3",
    chapter: "First fights",
    panels: [
      {
        id: "p09",
        where: "detroit",
        size: "wide",
        splash: true,
        tag: "Detroit · 2015",
        scene: "Rebuild it",
        art: "p09.webp",
        alt: "El-Sayed walks into a nearly empty Detroit Health Department office.",
        captions: [
          { text: "2015. Detroit's health department had been gutted and privatized. What's left: five city employees and 85 contractors.", pos: "tl" },
          { text: "Mayor Mike Duggan hands the job to a 30-year-old epidemiologist. His orders: rebuild it.", pos: "bl" },
        ],
        cites: [11, 12],
        prompt: "Wide 16:9 splash. A young Egyptian-American man in a suit and loosened tie walks into a nearly empty, dusty Detroit city office: overturned chairs, dead fluorescent lights, a few boxes. Morning light cuts through tall windows onto him like a spotlight. Detroit's east-side skyline through the glass. Heroic low angle, gold light, deep blue shadows.",
      },
      {
        id: "p10",
        where: "detroit",
        size: "third",
        tag: "Detroit schools",
        scene: "Glasses for kids",
        art: "p10.webp",
        alt: "A Detroit kid tries on new glasses in a mobile eye clinic.",
        captions: [{ text: "2016: free eye exams and free glasses for Detroit schoolkids, through a mobile clinic.", pos: "tl" }],
        cites: [13],
        prompt: "Square 1:1. Inside a mobile eye-clinic van parked outside a Detroit school, a grinning Black schoolgirl puts on her first pair of glasses and sees clearly; the blurry world behind her snaps into focus. Bright, joyful cyan and gold.",
      },
      {
        id: "p11",
        where: "detroit",
        size: "third",
        tag: "Detroit",
        scene: "SisterFriends",
        art: "p11.webp",
        alt: "Volunteer mentors with a new mother and her baby.",
        captions: [{ text: "His push on infant deaths leads to SisterFriends Detroit: mentors for new moms through the baby's first birthday.", pos: "tl" }],
        cites: [14],
        prompt: "Square 1:1. A young Detroit mother holding her baby on a porch, surrounded by two smiling volunteer women mentors with a bag of baby supplies. Warm sunrise light, soft magenta glow.",
      },
      {
        id: "p12",
        where: "detroit",
        size: "third",
        tag: "Michigan · 2018",
        scene: "The first run",
        art: "p12.webp",
        alt: "El-Sayed on stage at a rally, Bernie Sanders beside him.",
        captions: [
          { text: "2018: he runs for governor on single-payer health care. Bernie Sanders and AOC campaign with him.", pos: "tl" },
          { text: "He loses the primary. He doesn't quit.", pos: "bl" },
        ],
        cites: [15, 16, 17],
        prompt: "Square 1:1. A packed Michigan rally at night, confetti and phone lights. A young Egyptian-American candidate raises a fist at the mic; a white-haired older senator in a rumpled suit claps beside him. Then a hint of rain starting. Magenta and cyan stage light.",
      },
      {
        id: "p13",
        where: "queens",
        size: "half",
        tag: "Astoria · 2020",
        scene: "The upset",
        art: "p13.webp",
        alt: "Mamdani knocks on an Astoria row-house door at night. He is the only politician in the frame.",
        captions: [{ text: "2020: he knocks out a ten-year incumbent in Astoria by about 300 votes and goes to the State Assembly.", pos: "tl" }],
        sfx: { text: "UPSET!" },
        cites: [18],
        prompt: "Night in Astoria, Queens. One young South Asian man only: full dark beard, thick styled dark hair with volume on top, dark suit and blue polka-dot tie, clipboard, knocking on a brick row-house door under the elevated train. He is the only politician. No second man. No short-cropped hair. No black henley. No stethoscope. No lettering.",
      },
      {
        id: "p14",
        where: "queens",
        size: "half",
        tag: "New York · 2023",
        scene: "Free buses",
        art: "p14.webp",
        alt: "A packed city bus riding free.",
        captions: [
          { text: "He fights for a fare-free bus pilot. On five routes, ridership jumps about 30% on weekdays.", pos: "tl" },
          { text: "The platform on his site goes further: no fare on every city bus, plus priority lanes, queue jumps, and loading zones.", pos: "bl" },
        ],
        cites: [19, 40],
        prompt: "A crowded blue-and-white New York City bus at dusk, riders of every age boarding through all doors, no fare box, big smiles. Everyday riders only. No politicians. No henley. No stethoscope. No lettering.",
      },
      {
        id: "p15",
        where: "queens",
        size: "wide",
        splash: true,
        tag: "City Hall · 2021",
        scene: "Hunger strike",
        art: "p15.webp",
        alt: "Taxi drivers and Mamdani on hunger strike outside City Hall at night.",
        captions: [
          { text: "October 2021. Taxi drivers are drowning in medallion debt. He joins their hunger strike outside City Hall and gets arrested sitting in Broadway.", pos: "tl" },
          { text: "Day 15: a deal. Loans are cut to a $170,000 cap, with payments around $1,122 a month.", pos: "br" },
        ],
        sfx: { text: "DAY 15" },
        cites: [20, 21],
        prompt: "Night outside a grand city hall. Older immigrant taxi drivers in jackets on folding chairs with blankets, yellow cabs behind them. One thin young South Asian man with a full dark beard and styled dark hair sits among them, exhausted but unbowed. He is the only young man. No second politician. No short-cropped hair. No henley. Rain, yellow cab lights. No readable text.",
      },
    ],
  },
  {
    label: "Part 4",
    chapter: "Long odds",
    panels: [
      {
        id: "p16",
        where: "detroit",
        size: "half",
        tag: "Detroit · 2020–2025",
        scene: "Back to work",
        art: "p16.webp",
        alt: "El-Sayed at a microphone for his podcast, a copy of his book on the desk.",
        captions: [
          { text: "He writes Healing Politics, hosts the podcast America Dissected, and goes back to government as Wayne County's health director.", pos: "tl" },
        ],
        cites: [22, 23],
        prompt: "Landscape 4:3. Late night in a Detroit home studio: an Egyptian-American man in a sweater talks into a podcast microphone, a hardcover book on the desk, the Detroit skyline and the Guardian Building glowing through the window. Cozy gold light, cyan monitor glow.",
      },
      {
        id: "p17",
        where: "queens",
        size: "half",
        tag: "Manhattan · 2025",
        scene: "The long walk",
        art: "p17.webp",
        alt: "Mamdani walking down Broadway at night.",
        captions: [{ text: "October 2024: he runs for mayor, polling in single digits. June 2025: he walks the length of Manhattan overnight.", pos: "tl" }],
        bubbles: [{ who: "Mamdani", text: "New Yorkers deserve a mayor they can see, hear, even yell at.", pos: "right low" }],
        cites: [24, 25],
        prompt: "Landscape 4:3. Summer night on an empty Manhattan avenue, a lone young South Asian man in sneakers and rolled sleeves walks toward the camera, followers with phones trailing behind, skyscrapers glowing magenta and gold, steam rising from a manhole.",
      },
      {
        id: "p18",
        where: "queens",
        size: "wide",
        splash: true,
        tag: "New York · 2025",
        scene: "Hope is alive",
        art: "p18.webp",
        alt: "Mamdani on stage on election night, arms raised, confetti falling.",
        captions: [
          { text: "June 2025: he beats Andrew Cuomo in the Democratic primary, 56% to 44%.", pos: "tl" },
          { text: "November 4: elected mayor. New York's first Muslim mayor, first South Asian mayor, first African-born mayor.", pos: "bl" },
        ],
        bubbles: [{ who: "Mamdani", text: "Hope is alive!", pos: "right high", shout: true }],
        cites: [26, 27, 28],
        prompt: "Wide 16:9 splash. Election night in a packed Brooklyn venue: a young South Asian man in a dark suit raises both arms at the podium, a sea of cheering supporters, confetti and phone lights, huge gold and magenta stage lighting. Ecstatic, triumphant.",
      },
      {
        id: "p19",
        where: "queens",
        size: "half",
        tag: "City Hall station · Jan 1, 2026",
        scene: "The oath",
        art: "p19.webp",
        alt: "Mamdani sworn in at midnight in the old City Hall subway station.",
        captions: [{ text: "Just after midnight, January 1, 2026, he takes the oath in the old City Hall subway station.", pos: "tl" }],
        bubbles: [{ who: "Mamdani", text: "Never will we be accused of lacking the courage to try.", pos: "center low" }],
        cites: [29, 30],
        prompt: "Landscape 4:3. The decommissioned City Hall subway station at midnight: curved Guastavino tile arches, brass chandeliers, skylights. A young South Asian man in a dark coat raises his right hand, left hand on two Qurans held by his wife; a small circle of witnesses. Glowing gold and green tile light.",
      },
      {
        id: "p20",
        where: "detroit",
        size: "half",
        tag: "Michigan · 2025",
        scene: "Receipts",
        art: "p20.webp",
        alt: "El-Sayed launching his Senate campaign.",
        captions: [
          { text: "April 2025: he launches a run for U.S. Senate with a staff of four. Bernie Sanders endorses within hours.", pos: "tl" },
          { text: "His site states the platform in three lines: get money out of politics, put money in your pocket, and pass Medicare for All.", pos: "bl" },
        ],
        bubbles: [{ who: "El-Sayed", text: "If you want a fighter, I've got receipts.", pos: "right low" }],
        cites: [31, 32, 41],
        prompt: "Landscape 4:3. A small rented Detroit campaign office at night, folding tables, four staffers on laptops, a hand-painted banner (no readable text). An Egyptian-American man in rolled shirtsleeves grins and holds up a fistful of paper receipts. Gold desk lamps, cyan laptop glow.",
      },
    ],
  },
  {
    label: "Part 5",
    chapter: "Landing punches",
    panels: [
      {
        id: "p21",
        where: "queens",
        size: "two-thirds",
        tag: "New York · June 2026",
        scene: "Rent freeze",
        art: "p21.webp",
        alt: "Tenants cheering outside a Rent Guidelines Board vote.",
        captions: [
          { text: "June 25, 2026: the Rent Guidelines Board freezes the rent. 0% on one-year and two-year leases, for about a million rent-stabilized apartments.", pos: "tl" },
          { text: "That was the pledge on his campaign site: freeze the rent for every stabilized tenant. More than two million New Yorkers live in those apartments.", pos: "bl" },
        ],
        bubbles: [{ who: "Mamdani", text: "A historic victory for New York City tenants.", pos: "left low" }],
        sfx: { text: "FROZEN!" },
        cites: [33, 40],
        prompt: "Tenants cheering on the steps of a city building at dusk. Frost and ice crystals breaking off an apartment facade. One young South Asian man in a dark suit and blue polka-dot tie, full dark beard, thick styled dark hair, raising a fist with the crowd. He is the only politician in the frame. No second man. No black henley. No stethoscope. Blank protest signs with no readable words. No logos, no names.",
      },
      {
        id: "p22",
        where: "queens",
        size: "third",
        tag: "New York · 2026",
        scene: "2-K",
        art: "p22.webp",
        alt: "Toddlers in a bright new classroom.",
        captions: [
          { text: "Free, full-day child care for two-year-olds, starting this September.", pos: "tl" },
          { text: "The platform he ran on: free care from six weeks to five years, and childcare workers paid like public-school teachers.", pos: "bl" },
        ],
        cites: [34, 40],
        prompt: "A bright New York toddler classroom. Two-year-olds painting and stacking blocks. One parent waving goodbye at the door with relief. Warm joyful light. No politicians. No bearded men in suits. No henley. No stethoscope. No lettering on the walls.",
      },
      {
        id: "p23",
        where: "queens",
        size: "third",
        tag: "East Harlem · Hunts Point",
        scene: "City grocery",
        art: "p23.webp",
        alt: "A city-owned grocery store under construction.",
        captions: [
          { text: "The first sites for city-owned grocery stores: La Marqueta in East Harlem and The Peninsula in Hunts Point.", pos: "tl" },
          { text: "His site's plan: a network of city stores that pay no rent and no property tax, and sell at wholesale.", pos: "bl" },
        ],
        cites: [35, 40],
        prompt: "La Marqueta in East Harlem under an elevated railroad viaduct at dusk, market stalls being built out, crates of fresh produce, construction lights. Everyday shoppers and workers. No politicians. No henley. No stethoscope. No lettering.",
      },
      {
        id: "p24",
        where: "queens",
        size: "two-thirds",
        tag: "New York · Sept 2026",
        scene: "Delivery workers get paid",
        art: "p24.webp",
        alt: "Delivery workers on e-bikes in the rain, a giant check behind them.",
        captions: [{ text: "September 2026: the city wins a record $131.5 million from DoorDash for about 260,000 underpaid delivery workers.", pos: "tl" }],
        sfx: { text: "PAID!" },
        cites: [36],
        prompt: "Wide 2:1. A line of food-delivery workers on e-bikes in the rain on a New York avenue, insulated bags on their backs, raising fists and cheering as gold coins rain down around them. Neon storefront reflections, cyan and gold.",
      },
      {
        id: "p25",
        where: "detroit",
        size: "wide",
        splash: true,
        tag: "Michigan · Aug 4, 2026",
        scene: "The primary",
        art: "p25.webp",
        alt: "El-Sayed on primary night in Detroit, arms raised.",
        captions: [
          { text: "August 4, 2026. Nearly $65 million in outside money pours into the Democratic Senate primary, most of it against him.", pos: "tl" },
          { text: "He wins by fewer than 15,000 votes. His opponents endorse him the next day.", pos: "bl" },
        ],
        sfx: { text: "WON!" },
        cites: [37, 38],
        prompt: "Wide 16:9 splash. Primary night in Detroit: an Egyptian-American man in a dark suit bursts through a wall of floating dollar bills and attack-ad TV screens, fists raised, cheering crowd behind him. Detroit skyline and the Renaissance Center glowing magenta and gold. Explosive, triumphant.",
      },
    ],
  },
  {
    label: "Part 6",
    chapter: "Same street",
    panels: [
      {
        id: "p26",
        where: "both",
        size: "wide",
        splash: true,
        tag: "The road to the Capitol",
        scene: "Two roads meet",
        art: "p26.webp",
        alt: "Mamdani and El-Sayed walk side by side up a rain-slick avenue toward the Capitol.",
        captions: [
          { text: "One already runs the biggest city in America.", pos: "tl" },
          { text: "One faces Republican Mike Rogers for U.S. Senate on November 3, 2026. The fight isn't over.", pos: "bl" },
        ],
        cites: [39],
        prompt: "Wide 16:9 splash, matching the fighter-select screen: a rain-slick avenue at night leading to the lit U.S. Capitol dome. Seen from behind and slightly to the side, Zohran Mamdani (dark suit, polka-dot tie) and Abdul El-Sayed (black henley) walk side by side toward the Capitol, puddles reflecting neon magenta, cyan and gold. Epic, hopeful, cinematic.",
      },
    ],
  },
  {
    label: "Issue #2",
    chapter: "The Healer",
    panels: [
      {
        id: "h01",
        where: "detroit",
        size: "wide",
        splash: true,
        tag: "Missouri · the woman they tried to smear",
        scene: "The healer",
        art: "h01.webp",
        alt: "An older Egyptian nurse in a white coat stands like a superhero, gold light around her, children safe behind her cape.",
        captions: [
          { text: "Rogers went after his mom on the debate stage. This is who she is.", pos: "tl" },
          { text: "Fatten Elkomy. Psychiatric nurse practitioner. Never charged. Still on the job.", pos: "bl" },
        ],
        cites: [47, 48, 49],
        prompt:
          "Bold American comic-book splash, heavy black ink, halftone dots, rain-slick night with neon gold, magenta, and cyan. No text, no lettering, no logos, no names. An older Egyptian woman in her late sixties, short dark hair silver at the temples, warm brown eyes, dignified closed-mouth smile. Chibi proportions: large head, short athletic body, same face language as the rest of this fighter-select comic. White nurse-practitioner coat flaring behind her like a gold-lined cape. Teal scrubs underneath. A stethoscope across her chest glowing like a gold shield. Small children of several backgrounds stand safe behind the coat, holding the hem. Attack-ad headlines and a watchlist form bounce off the gold light and tear into confetti. Low heroic angle, clinic windows blazing gold behind her. She looks like a superhero because the work is the power.",
      },
      {
        id: "h02",
        where: "detroit",
        size: "half",
        tall: true,
        tag: "Alexandria · 1983",
        scene: "She trained as a doctor first",
        art: "h02.webp",
        alt: "A young Egyptian woman in a white coat on the steps of a medical school by the sea.",
        captions: [
          { text: "1983. She graduates from Alexandria University's School of Medicine.", pos: "tl" },
          { text: "That is her training. That is the start of the work.", pos: "bl" },
        ],
        cites: [49],
        prompt:
          "Bold American comic-book illustration, heavy black ink, halftone, gold Mediterranean light. No text. Portrait 3:4. A young Egyptian woman in a fresh white medical coat on stone steps beside a seafront medical school, lighthouse ghosted in the sky. Hopeful, proud, not grim. Chibi proportions matching the series. Warm gold with a cyan rim light.",
      },
      {
        id: "h03",
        where: "detroit",
        size: "half",
        tag: "Columbia, Missouri",
        scene: "Then she kept training",
        art: "h03-chibi.webp",
        alt: "The same woman older, in a clinic, listening to a patient.",
        captions: [
          { text: "In the United States she earns dual master's degrees in health administration and health informatics, then a master's and a doctorate in psychiatric and mental-health nursing.", pos: "tl" },
          { text: "She becomes a board-certified psychiatric nurse practitioner. She has worked at a community mental-health agency in Missouri since 2018.", pos: "bl" },
        ],
        cites: [49, 50],
        prompt:
          "Small rain-streaked clinic office. Ordinary desk lamp, no halo. An older Egyptian woman matching the clinic nurse: short dark hair going silver, weathered brown skin, laugh lines, white coat over teal scrubs, no hijab. She sits across from a tired young man, listening, slight smile. Clipboard on the desk. Rain on the windows. She is in her fifties, not a child, not a young kawaii girl. No lettering.",
      },
      {
        id: "h04",
        where: "detroit",
        size: "wide",
        tag: "Columbia, Missouri · 2026",
        scene: "Kids still get the Friday",
        art: "h04.webp",
        alt: "The nurse sits with schoolchildren, listening, a cape of gold light behind her chair.",
        captions: [
          { text: "A local school posted that she would start as counselor in April 2026, every other Friday, eight to three.", pos: "tl" },
          { text: "Thirteen years as a psychiatric and mental-health provider. That is the calendar. That is the cape.", pos: "bl" },
        ],
        cites: [49],
        prompt:
          "One older Egyptian woman only, matching the attached clinic nurse: short dark hair silver at the temples, weathered brown skin, laugh lines, white coat over teal scrubs, teal clogs, no hijab. She sits in a small classroom circle with schoolchildren of several backgrounds. One child shows her a crayon drawing of a house. Soft gold light around her chair. The children do not look like her. No second nurse. No duplicate of her face among the kids. No lettering.",
      },
    ],
  },
  {
    label: "Issue #2",
    chapter: "The orphans",
    panels: [
      {
        id: "h05",
        where: "detroit",
        size: "two-thirds",
        tall: true,
        tag: "1999–2004",
        scene: "The job she named",
        art: "h05.webp",
        alt: "The nurse at a charity desk covered in child-sponsorship files and kids' drawings.",
        captions: [
          { text: "In the early 2000s she worked at a Missouri humanitarian aid office. Court files from those years show transfer requests labeled for child sponsorship and for orphans.", pos: "tl" },
          { text: "In 2004 she told the Columbia Daily Tribune: \"I've been working there serving orphans and children with at least one deceased parent, and it breaks my heart they're not going to get any help.\"", pos: "bl" },
        ],
        cites: [48],
        prompt:
          "Modest humanitarian aid office around 2000. An older Egyptian woman matching the clinic nurse: short dark hair going silver, weathered brown skin, laugh lines, white coat over street clothes, no hijab, no nurse cap. She holds a child's crayon drawing of a house like it is the most important document in the room. Desk stacked with folders and more crayon drawings. Gray American street through the window. Gold light on the drawings. No flags, no weapons, no lettering.",
      },
      {
        id: "h06",
        where: "detroit",
        size: "third",
        tag: "The record",
        scene: "They interviewed her. They did not charge her.",
        art: "h06.webp",
        alt: "The nurse walks out of a federal building into gold light, files remaining behind her unmarked.",
        captions: [
          { text: "She told the Tribune that FBI agents interviewed her for three hours about that work.", pos: "tl" },
          { text: "She was never accused of wrongdoing, never charged, and never named as a defendant. Fact-checkers found no evidence she knew of any crime at the office.", pos: "bl" },
        ],
        cites: [48],
        prompt:
          "Tall comic panel, heavy ink, halftone, no text. An Egyptian woman in a white coat walks down the steps of a gray federal building into a column of gold light. Behind her, a stack of files sits unmarked. She does not look hunted. She looks finished with the questions and late for the next patient. Chibi, chin up, cape-coat catching wind. Cyan rain, gold sunbreak.",
      },
    ],
  },
  {
    label: "Issue #2",
    chapter: "The smear",
    panels: [
      {
        id: "h07",
        where: "detroit",
        size: "wide",
        tag: "Michigan · Oct. 8, 2026",
        scene: "He went after her on live television",
        art: "h07.webp",
        alt: "A TV debate: an older gray-haired man jabs a finger from one podium; El-Sayed stands calm at the other. Two people only.",
        captions: [
          { text: "On the Senate debate stage, Rogers suggested Flock cameras bothered his opponent because \"someone in your family that might be on a watchlist.\"", pos: "tl" },
          { text: "El-Sayed: \"You're gonna go after my mom?\" Rogers said her workplace \"was indicted for funneling money\" to al-Qaeda. \"That's your mom. My mom worked at a small chamber of commerce. I'll put her up any day for that.\"", pos: "bl" },
        ],
        cites: [47],
        prompt:
          "TV debate studio with two wooden podiums and harsh spotlights. Empty LED walls with abstract gold graphics and no readable words. Left podium: older white man in his sixties, thinning steel-gray hair combed back, receding hairline, charcoal suit, shouting, jabbing a finger. Right podium: the same Egyptian-American man as the attached references, now in a navy suit and dark tie. Short close-cropped dark hair covering the whole scalp, no receding hairline, short full jaw beard that is not a goatee and not a long bushy beard, thick eyebrows, rounder cheeks, slight closed-mouth smile, unbothered. Only two people. No statue, no golden figure, no nurse, no children, no halo, no lettering.",
      },
      {
        id: "h08",
        where: "detroit",
        size: "half",
        tag: "What the case actually was",
        scene: "Say the Justice Department part out loud",
        art: "h08.webp",
        alt: "A gold stethoscope pins a true court paper over a fake terror headline.",
        captions: [
          { text: "The U.S. branch was later convicted of illegal transfers to Iraq under sanctions. The Justice Department said that indictment \"does not charge any of the defendants with material support of terrorism, nor does it allege that they knowingly financed acts of terror.\"", pos: "tl" },
          { text: "She was not one of those defendants.", pos: "bl" },
        ],
        cites: [48, 52],
        prompt:
          "Older Egyptian woman matching the clinic nurse: short dark hair going silver, weathered brown skin, white coat, teal scrubs, no hijab. She pins a blank court paper to a wall with a gold stethoscope, covering a crumpled screaming red attack-ad poster with no readable words. Calm face. Magenta scare-poster vs gold clinical light. No lettering.",
      },
      {
        id: "h09",
        where: "detroit",
        size: "half",
        tag: "The line he wanted",
        scene: "He had nothing on the son, so he reached for the mother",
        art: "h09.webp",
        alt: "El-Sayed at the debate podium, unbothered, while Rogers points from the other stand. Two people only.",
        captions: [
          { text: "El-Sayed: he wants this to be about anything but his own record. \"Going after my mom, my sister, but he's got nothing to actually say about me.\"", pos: "tl" },
        ],
        cites: [47],
        prompt:
          "Closer on the same two-podium debate. Egyptian-American man matching the attached fighter: short close-cropped dark hair covering the whole scalp, short full jaw beard, thick eyebrows, rounder cheeks, navy suit, slight closed-mouth smile, unbothered at his podium. Older gray-haired man pointing from the left. Only two people. No statue, no golden figure, no nurse, no children, no halo, no lettering.",
      },
    ],
  },
  {
    label: "Issue #2",
    chapter: "Still on the job",
    panels: [
      {
        id: "h11",
        where: "detroit",
        size: "wide",
        splash: true,
        tag: "The last panel",
        scene: "The cape is a coat",
        art: "h11.webp",
        alt: "The nurse walks toward a clinic at dawn, coat flaring like a cape, gold sun at her back, children and patients in the windows.",
        captions: [
          { text: "She is still a psychiatric nurse practitioner in Missouri. Active license. Clinic addresses on the public registry.", pos: "tl" },
          { text: "A Senate candidate tried to turn her into a watchlist. The record turns her into what she is: a healer. The coat is the cape.", pos: "bl" },
        ],
        cites: [50, 48],
        prompt:
          "One older Egyptian woman only, matching the attached clinic nurse: short dark hair silver at the temples, weathered brown skin, laugh lines, white coat flaring like a cape over teal scrubs, teal clogs, no hijab. She walks toward a small clinic at dawn, patients waving in the windows, gold sunrise at her back. Adult face in her late fifties, not a child. No lettering.",
      },
    ],
  },
  {
    label: "Part 7",
    chapter: "The platforms",
    panels: [
      { id: "p27", where: "queens", size: "third", tag: "New York", scene: "Freeze the rent", art: "p27.webp", alt: "Mamdani in front of an apartment building as frost breaks off it.", captions: [{ text: "Freeze the rent for every stabilized tenant. More than two million New Yorkers live in those apartments.", pos: "tl" }], cites: [40], prompt: "Mamdani, rent freeze, ice on an apartment building." },
      { id: "p28", where: "queens", size: "third", tag: "New York", scene: "Fast, fare-free buses", art: "p28.webp", alt: "Mamdani beside a city bus in a priority lane.", captions: [{ text: "End the fare on every city bus. Speed them with priority lanes, queue-jump signals, and loading zones.", pos: "tl" }], cites: [40], prompt: "Mamdani, fare-free bus in a priority lane." },
      { id: "p29", where: "queens", size: "third", tag: "New York", scene: "Community safety", art: "p29.webp", alt: "Mamdani with outreach workers helping a rider in a subway station.", captions: [{ text: "A Department of Community Safety: mental-health teams, outreach workers in 100 subway stations, and more funding to prevent hate violence. Police keep a role. They stop being the safety net.", pos: "tl" }], cites: [40], prompt: "Mamdani, subway outreach, no fight." },
      { id: "p30", where: "queens", size: "third", tag: "New York", scene: "No-cost childcare", art: "p30.webp", alt: "Mamdani in the doorway of a toddler classroom.", captions: [{ text: "Free childcare from six weeks to five years. Childcare workers paid on par with public-school teachers.", pos: "tl" }], cites: [40], prompt: "One young South Asian man only: full dark beard, thick styled dark hair with volume on top, dark suit and blue polka-dot tie, in the doorway of a toddler classroom. He is the only politician. No second man. No henley. No stethoscope. No lettering." },
      { id: "p31", where: "queens", size: "third", tag: "New York", scene: "City-owned groceries", art: "p31.webp", alt: "Mamdani inside a city grocery stacked with produce.", captions: [{ text: "A network of city-owned stores. No rent, no property tax, and wholesale prices, so the savings go to shoppers.", pos: "tl" }], cites: [40], prompt: "One young South Asian man only: full dark beard, thick styled dark hair with volume on top, dark suit and blue polka-dot tie, inside a city grocery stacked with produce. He is the only politician. No second man. No henley. No stethoscope. No lettering." },
      { id: "p32", where: "queens", size: "third", tag: "New York", scene: "200,000 homes", art: "p32.webp", alt: "Mamdani in front of new apartment buildings and construction workers.", captions: [{ text: "200,000 new permanently affordable, union-built, rent-stabilized homes over 10 years. A project that is 100% affordable gets fast-tracked.", pos: "tl" }], cites: [40], prompt: "One young South Asian man only: full dark beard, thick styled dark hair with volume on top, dark suit and blue polka-dot tie, in front of new apartment buildings with construction workers. He is the only politician. No second man. No henley. No stethoscope. No lettering." },
      { id: "p33", where: "queens", size: "third", tag: "New York", scene: "Bad landlords", art: "p33.webp", alt: "Mamdani with city workers repairing a neglected apartment hallway.", captions: [{ text: "If the owner will not make the repair, the city does it and sends the bill. In the worst cases, the city takes the building.", pos: "tl" }], cites: [40], prompt: "Mamdani, city repair crew in a hallway." },
      { id: "p34", where: "queens", size: "third", tag: "New York", scene: "Who pays", art: "p34.webp", alt: "Mamdani between glass towers and a working family.", captions: [{ text: "Match New Jersey's 11.5% corporate tax. A 2% city tax on income over $1 million. Another $1 billion from procurement reform, auditors, and fines on corrupt landlords.", pos: "tl" }], cites: [40], prompt: "One young South Asian man only: full dark beard, thick styled dark hair with volume on top, dark suit and blue polka-dot tie, standing between glass office towers and a working family. He is the only politician. No second man. No short-cropped hair. No black henley. No stethoscope. No lettering." },
      { id: "p35", where: "queens", size: "third", tag: "New York", scene: "$30 by 2030", art: "p35.webp", alt: "Mamdani with workers holding pay envelopes.", captions: [{ text: "Raise New York City's minimum wage to $30 an hour by 2030.", pos: "tl" }], cites: [46], prompt: "One young South Asian man only: full dark beard, thick styled dark hair with volume on top, dark suit and blue polka-dot tie, standing with city workers in safety vests holding pay envelopes. He is the only politician. No second man. No short-cropped hair. No black henley. No stethoscope. No lettering." },
      { id: "p36", where: "detroit", size: "third", tag: "Michigan", scene: "Medicare for All", art: "p36.webp", alt: "El-Sayed in a public clinic as patients get care.", captions: [{ text: "Medicare for every American, cradle to grave, including vision, dental, and hearing. No premiums, copays, or deductibles. He also wants medical debt abolished.", pos: "tl" }], cites: [42], prompt: "El-Sayed, public clinic." },
      { id: "p37", where: "detroit", size: "third", tag: "Michigan", scene: "Money out of politics", art: "p37.webp", alt: "El-Sayed sweeping corporate cash off a table.", captions: [{ text: "Never a dime of corporate money. Overturn Citizens United. Ban outside spending by super PACs. Public election funding and spending caps.", pos: "tl" }], cites: [43], prompt: "El-Sayed, sweeping dark money aside." },
      { id: "p38", where: "detroit", size: "third", tag: "Michigan", scene: "Put money in your pocket", art: "p38.webp", alt: "El-Sayed at a Michigan kitchen table with a working family.", captions: [{ text: "Tax capital gains over $1 million like wages. A federal tax exemption on the first $50,000. One good job should raise a family.", pos: "tl" }], cites: [44], prompt: "El-Sayed, kitchen table, money staying with a family." },
      { id: "p39", where: "detroit", size: "third", tag: "Michigan", scene: "Housing", art: "p39.webp", alt: "El-Sayed handing keys to a family in front of a new house.", captions: [{ text: "A building boom and a federal renter bill of rights. Ban large corporations from owning homes they speculate on.", pos: "tl" }], cites: [44], prompt: "El-Sayed, family getting house keys." },
      { id: "p40", where: "detroit", size: "third", tag: "Michigan", scene: "Clean water", art: "p40.webp", alt: "El-Sayed on a Great Lakes shore as workers pull lead pipes.", captions: [{ text: "At least 50 gallons of clean water a person a day. Bills capped at 2% of income. Every lead pipe in Michigan out by 2030. Shut down Line 5.", pos: "tl" }], cites: [43], prompt: "El-Sayed, clean water, lead pipes, Line 5." },
      { id: "p41", where: "detroit", size: "third", tag: "Michigan", scene: "Schools", art: "p41.webp", alt: "El-Sayed in a public-school classroom with a teacher and students.", captions: [{ text: "Universal childcare and pre-K. A $60,000 minimum for teachers. A debt-free path through college or an apprenticeship.", pos: "tl" }], cites: [44], prompt: "El-Sayed, public school classroom." },
      { id: "p42", where: "detroit", size: "half", tag: "Michigan", scene: "Data centers", art: "p42.webp", alt: "El-Sayed standing between a neighborhood and a data center.", captions: [{ text: "Data centers pay their own power, so household rates do not rise. Closed-loop cooling, so they do not drain the water. Neighbors get a say.", pos: "tl" }], cites: [45], prompt: "El-Sayed between houses and a data center." },
      { id: "p43", where: "detroit", size: "half", tag: "Michigan", scene: "Diplomacy", art: "p43.webp", alt: "El-Sayed at a diplomatic table.", captions: [{ text: "A foreign policy centered on diplomacy, cooperation, and human rights. No blank-check funding for foreign militaries.", pos: "tl" }], cites: [43], prompt: "El-Sayed at a diplomacy table." },
    ],
  },
];

export const PLANKS = [
  { where: "queens", who: "Mamdani", title: "Freeze the rent", cites: [40], text: "Freeze the rent for every stabilized tenant. His site says more than two million New Yorkers live in those apartments." },
  { where: "queens", who: "Mamdani", title: "Fast, fare-free buses", cites: [40], text: "End the fare on every city bus. Speed them with priority lanes, queue-jump signals, and loading zones so double-parkers stay out of the way." },
  { where: "queens", who: "Mamdani", title: "Community safety", cites: [40], text: "A Department of Community Safety: mental-health crisis response, outreach workers in 100 subway stations, gun-violence programs, and an 800% increase for hate-violence prevention. Police keep a role. They stop being the safety net." },
  { where: "queens", who: "Mamdani", title: "No-cost childcare", cites: [40], text: "Free childcare from six weeks to five years. Childcare workers paid on par with public-school teachers." },
  { where: "queens", who: "Mamdani", title: "City-owned groceries", cites: [40], text: "A network of city-owned stores. No rent, no property tax, and wholesale prices, so the savings go to shoppers." },
  { where: "queens", who: "Mamdani", title: "200,000 homes", cites: [40], text: "Triple production of permanently affordable, union-built, rent-stabilized homes: 200,000 new units over 10 years. Any project that is 100% affordable gets fast-tracked." },
  { where: "queens", who: "Mamdani", title: "Bad landlords", cites: [40], text: "One office for code enforcement. If the owner will not make the repair, the city does it and sends the bill. In the worst cases, the city takes the building." },
  { where: "queens", who: "Mamdani", title: "Who pays", cites: [40], text: "Match New Jersey's 11.5% corporate tax, about $5 billion. A 2% city tax on income over $1 million. Another $1 billion from procurement reform, more tax auditors, and fines on corrupt landlords." },
  { where: "queens", who: "Mamdani", title: "$30 by 2030", cites: [46], text: "Raise New York City's minimum wage to $30 an hour by 2030." },
  { where: "detroit", who: "El-Sayed", title: "Medicare for All", cites: [42], text: "Medicare for every American, cradle to grave, including vision, dental, and hearing. No premiums, copays, or deductibles. Automatic, and accepted everywhere. Extra union or employer plans can remain. He also wants medical debt abolished." },
  { where: "detroit", who: "El-Sayed", title: "Money out of politics", cites: [43], text: "He says he has never taken a dime of corporate money and never will. Overturn Citizens United. Ban outside spending by corporate 501(c)(4)s, super PACs, and 527s. Public election funding and spending caps." },
  { where: "detroit", who: "El-Sayed", title: "Put money in your pocket", cites: [44], text: "Tax capital gains over $1 million like wages, close the stepped-up basis loophole, and tax wealth over $1 billion. A federal tax exemption on the first $50,000. One good job should raise a family." },
  { where: "detroit", who: "El-Sayed", title: "Housing", cites: [44], text: "A building boom and a federal renter bill of rights. Ban large corporations from owning homes they speculate on, and ban software that lets landlords fix rents together." },
  { where: "detroit", who: "El-Sayed", title: "Clean water", cites: [43], text: "At least 50 gallons of clean water a person a day. Bills capped at 2% of household income, and no shutoffs for families who cannot pay. Every lead pipe in Michigan out by 2030. Shut down Line 5." },
  { where: "detroit", who: "El-Sayed", title: "Schools", cites: [44], text: "Universal childcare and pre-K. A $60,000 minimum salary for teachers. Fully fund the Individuals with Disabilities Education Act. A debt-free, tuition-free path through college or an apprenticeship." },
  { where: "detroit", who: "El-Sayed", title: "Data centers", cites: [45], text: "The centers pay their own power, so household rates do not rise. Closed-loop cooling, so they do not drain or pollute the water. They deliver the local jobs they promise, built by contractors with registered apprenticeships. Neighbors get a say." },
  { where: "detroit", who: "El-Sayed", title: "Diplomacy", cites: [43], text: "A foreign policy centered on diplomacy, cooperation, and human rights. No blank-check funding for foreign militaries, including Egypt, Israel, Saudi Arabia, and the UAE. He supports an immediate arms embargo on Israel." },
];

export const SOURCES = [
  { n: 1, label: "CNN, Zohran Mamdani fast facts.", url: "https://www.cnn.com/politics/zohran-mamdani-fast-facts" },
  { n: 2, label: "The Africa Report, 10 things about Zohran Mamdani.", url: "https://www.theafricareport.com/386712/zohran-mamdani-10-things-about-uganda-born-democratic-nominee-for-new-york-city-mayor/" },
  { n: 3, label: "Bridge Michigan, who is Abdul El-Sayed.", url: "https://bridgemi.com/michigan-government/who-is-abdul-el-sayed-what-to-know-about-michigan-democrats-us-senate-winner/" },
  { n: 4, label: "El-Sayed for Senate, about.", url: "https://abdulforsenate.com/about/" },
  { n: 5, label: "University of Michigan Record, Rhodes Scholar announcement.", url: "https://record.umich.edu/articles/u-m-dual-md-phd-student-named-rhodes-scholar/" },
  { n: 6, label: "Columbia Medicine, alumni profile.", url: "https://www.vagelos.columbia.edu/about-us/columbia-medicine-magazine/archives/fall-winter-2016/alumni-news-notes/alumni-profile-abdul-el-sayed14" },
  { n: 7, label: "Columbia Mailman School, El-Sayed takes health reins in Detroit.", url: "https://www.publichealth.columbia.edu/news/mailmans-el-sayed-takes-health-reins-detroit" },
  { n: 8, label: "Vice, Madhur Jaffrey stars in \"Nani.\"", url: "https://www.vice.com/en/article/madhur-jaffrey-nani-rap-video/" },
  { n: 9, label: "Brick Underground, housing counselors at Chhaya.", url: "https://www.brickunderground.com/live/how-owners-facing-foreclosure-get-help-housing-counselors-chhaya-mamdani" },
  { n: 10, label: "PBS NewsHour, how Mamdani rose from Queens lawmaker to mayor.", url: "https://www.pbs.org/newshour/politics/how-zohran-mamdani-rose-from-queens-lawmaker-to-mayor-of-new-york" },
  { n: 11, label: "STAT, Detroit's health director.", url: "https://www.statnews.com/2016/05/03/detroit-health-director/" },
  { n: 12, label: "American Rhodes Scholars, El-Sayed named Detroit health director.", url: "https://www.americanrhodes.org/news-1071.html" },
  { n: 13, label: "WDET, free eye exams and glasses for DPSCD students.", url: "https://wdet.org/posts/2016/10/12/83985-new-program-provides-free-eye-exam-and-glasses-to-dpscd-students" },
  { n: 14, label: "City of Detroit, infant mortality drop and SisterFriends.", url: "https://detroitmi.gov/news/mayor-duggan-and-dr-khaldun-announce-historic-drop-infant-mortality-rate-city-detroit-2019-had" },
  { n: 15, label: "Detroit News, El-Sayed's MichCare plan.", url: "https://www.detroitnews.com/story/news/local/michigan/2018/06/06/el-sayed-universal-health-michigan/677394002/" },
  { n: 16, label: "WKAR, Bernie Sanders endorses El-Sayed.", url: "https://www.wkar.org/politics-government/2018-07-26/bernie-sanders-endorses-el-sayed-in-michigans-governors-race" },
  { n: 17, label: "Bridge Michigan, Whitmer wins 2018 primary.", url: "https://bridgemi.com/michigan-government/gretchen-whitmer-wins-democratic-primary-michigan-governor/" },
  { n: 18, label: "PoliticsNY, Mamdani unseats Simotas.", url: "https://politicsny.com/2020/07/22/dsa-backed-mamdani-unseats-simotas-in-36-ad-race/" },
  { n: 19, label: "MTA, fare-free bus pilot report.", url: "https://www.mta.info/document/177466" },
  { n: 20, label: "THE CITY, cabbies go on hunger strike.", url: "https://www.thecity.nyc/2021/10/21/nyc-cabbies-go-on-hunger-strike-taxi-medallion-debts/" },
  { n: 21, label: "City & State, taxi drivers' victory.", url: "https://www.cityandstateny.com/politics/2021/11/activist-lawmakers-share-taxi-drivers-victory/186641/" },
  { n: 22, label: "Abrams Books, Healing Politics.", url: "https://www.abramsbooks.com/product/healing-politics_9781683358138/" },
  { n: 23, label: "Wayne County, El-Sayed joins Health, Human & Veterans Services.", url: "https://www.waynecountymi.gov/News/Executive/2022/Dr.-Abdul-El-Sayed-joins-Health-Human-Veterans-Services-Department" },
  { n: 24, label: "Hell Gate, Mamdani goes the distance.", url: "https://hellgatenyc.com/zohran-mamdani-goes-the-distance/" },
  { n: 25, label: "Zohran Mamdani on X, after the Manhattan walk.", url: "https://x.com/ZohranKMamdani/status/1937133937316233269" },
  { n: 26, label: "amNY, ranked-choice primary results.", url: "https://www.amny.com/news/mamdani-democratic-primary-ranked-choice-vote-win/" },
  { n: 27, label: "NBC News, New York City mayor results.", url: "https://www.nbcnews.com/politics/2025-elections/new-york-city-mayor-results" },
  { n: 28, label: "TIME, Mamdani's victory speech.", url: "https://time.com/7331243/watch-zohran-mamdani-victory-speech/" },
  { n: 29, label: "CBS New York, swearing-in at the old City Hall station.", url: "https://www.cbsnews.com/newyork/news/zohran-mamdani-swearing-in-old-city-hall-station/" },
  { n: 30, label: "NYC Mayor's Office, inaugural address.", url: "https://www.nyc.gov/mayors-office/news/2026/01/mayor-zohran-mamdani-inaugural-address" },
  { n: 31, label: "Michigan Advance, El-Sayed enters U.S. Senate race.", url: "https://michiganadvance.com/2025/04/17/el-sayed-enters-race-for-michigans-u-s-senate-seat/" },
  { n: 32, label: "Bridge Michigan, \"If you want a fighter, I've got receipts.\"", url: "https://bridgemi.com/michigan-government/abdul-el-sayed-us-senate-run-if-you-want-fighter-ive-got-receipts/" },
  { n: 33, label: "Gothamist, Rent Guidelines Board approves rent freeze.", url: "https://gothamist.com/news/nyc-rent-guidelines-board-approves-2-year-rent-freeze-fulfilling-mamdani-campaign-pledge" },
  { n: 34, label: "NYC Mayor's Office, first 2-K communities.", url: "https://www.nyc.gov/mayors-office/news/2026/03/mayor-mamdani-and-governor-hochul-announce-first-four-communitie" },
  { n: 35, label: "TIME, city-owned grocery stores.", url: "https://time.com/article/2026/05/21/mamdani-city-owned-grocery-stores-east-harlem-manhattan-the-bronx/" },
  { n: 36, label: "NYC Mayor's Office, $131.5 million from DoorDash.", url: "https://www.nyc.gov/mayors-office/news/2026/09/mayor-mamdani-wins-record--131-5-million-from-doordash-for-deliv" },
  { n: 37, label: "Michigan Advance, El-Sayed wins the Senate primary.", url: "https://michiganadvance.com/2026/08/05/abdul-el-sayed-squeaks-out-win-over-haley-stevens-in-hotly-contested-democratic-us-senate-primary/" },
  { n: 38, label: "CNBC, Michigan Senate primary.", url: "https://www.cnbc.com/2026/08/04/abdul-el-sayed-haley-stevens-michigan-primary.html" },
  { n: 39, label: "Washington Post, Michigan Senate poll.", url: "https://www.washingtonpost.com/politics/2026/09/17/michigan-senate-race-poll-finds-abdul-el-sayed-has-narrow-edge-over-mike-rogers/" },
  { n: 40, label: "Zohran for NYC, platform.", url: "https://web.archive.org/web/20250702081752/https://www.zohranfornyc.com/" },
  { n: 41, label: "El-Sayed for Senate, priorities.", url: "https://abdulforsenate.com/priorities/" },
  { n: 42, label: "El-Sayed for Senate, Medicare for All.", url: "https://abdulforsenate.com/priority/medicare-for-all-the-path-to-a-healthier-america/" },
  { n: 43, label: "El-Sayed for Senate, money out of politics.", url: "https://abdulforsenate.com/priority/money-out-of-politics/" },
  { n: 44, label: "El-Sayed for Senate, money in your pocket.", url: "https://abdulforsenate.com/priority/money-in-your-pocket/" },
  { n: 45, label: "El-Sayed for Senate, data-center terms of engagement.", url: "https://abdulforsenate.com/2026/01/datacenters/" },
  { n: 46, label: "Zohran for NYC, $30-by-2030 canvass.", url: "https://volunteer.zohranfornyc.com/canvass-for-zohran-with-the-uaw" },
  { n: 47, label: "HuffPost, Rogers goes after El-Sayed's mother in the Michigan Senate debate.", url: "https://www.huffpost.com/entry/mike-rogers-pulls-the-your-mom-card-on-el-sayed-in-michigan-senate-debate_n_6ac7b573e4b09d2661d5b26c" },
  { n: 48, label: "Snopes, claim linking El-Sayed's mother to a charity and terrorist groups is missing key context.", url: "https://www.snopes.com/news/2026/08/25/el-sayed-mother-charity-terrorism/" },
  { n: 49, label: "Islamic School of Columbia-Missouri, counselor biography for Fatten Elkomy.", url: "http://www.theiscm.net/councellor.html" },
  { n: 50, label: "NPPES NPI Registry, Fatten F. Elkomy, psychiatric / mental-health nurse practitioner.", url: "https://npiregistry.cms.hhs.gov/provider-view/1316388754" },
  { n: 52, label: "Justice Department, Jan. 16, 2008: the indictment does not charge material support of terrorism.", url: "https://www.justice.gov/archive/opa/pr/2008/January/08_nsd_029.html" },
];
