// Two Roads to the Capitol: the comic script.
//
// Each panel's `art` is a file name in art/story/. While it is null the page
// draws a flat placeholder. `prompt` is the Makko art prompt for that panel;
// it is not shown on the page. `cites` are numbers in SOURCES.
//
// Sizes on a 6-column grid: wide = 6, two-thirds = 4, half = 3, third = 2.
// `tall` spans two rows. Every row has to add up to 6.
//
// Facts were checked against the sources as of September 27, 2026.

export const STYLE =
  "Bold American comic-book illustration, heavy black ink outlines, halftone dot shading, " +
  "rain-slick night lighting with neon magenta, cyan and gold accents, same painted-comic style " +
  "as the Capitol Crashers fighter-select screen. No text, no lettering, no speech bubbles.";

export const PAGES = [
  {
    label: "Part 1",
    chapter: "Two beginnings",
    panels: [
      {
        id: "p01",
        where: "queens",
        size: "half",
        tall: true,
        tag: "Kampala · 1991",
        scene: "Kampala, Uganda",
        art: null,
        alt: "A newborn in Kampala, held by his mother, a filmmaker, and his father, a scholar.",
        captions: [
          { text: "October 18, 1991. Kampala, Uganda. Zohran Kwame Mamdani is born, his middle name a tribute to Kwame Nkrumah.", pos: "tl" },
          { text: "His mother is filmmaker Mira Nair. His father is Mahmood Mamdani, a scholar of colonialism.", pos: "bl" },
        ],
        cites: [1, 2],
        prompt: "Portrait 3:4. Warm golden-hour Kampala hillside with red-earth roads and jacaranda trees. A young Indian-American woman filmmaker and a Ugandan-Indian scholar with glasses cradle a newborn wrapped in a patterned cloth. Loving, hopeful mood; soft gold light with a magenta rim light.",
      },
      {
        id: "p02",
        where: "detroit",
        size: "half",
        tag: "Southeast Michigan · 1984",
        scene: "Detroit, 1984",
        art: null,
        alt: "An Egyptian engineer walks toward Wayne State University in Detroit.",
        captions: [
          { text: "October 31, 1984. Southeast Michigan. Abdulrahman \"Abdul\" El-Sayed is born.", pos: "tl" },
          { text: "His father came from Alexandria, Egypt, in 1979 to earn an engineering Ph.D. at Wayne State.", pos: "bl" },
        ],
        cites: [3, 4],
        prompt: "Landscape 4:3. Early-1980s Detroit in autumn: a young Egyptian man with a mustache, carrying engineering books, walks past Wayne State University's buildings with the Detroit skyline behind. Faded ghost-image of the Alexandria waterfront and lighthouse in the sky above him. Cool blue dusk with red and cyan neon accents.",
      },
      {
        id: "p03",
        where: "detroit",
        size: "half",
        tag: "Bloomfield Hills",
        scene: "Three-sport captain",
        art: null,
        alt: "A teenage El-Sayed in lacrosse gear under stadium lights.",
        captions: [{ text: "At Andover High he captains three teams at once: football, wrestling and lacrosse.", pos: "tl" }],
        sfx: { text: "CRACK!" },
        cites: [5],
        prompt: "Landscape 4:3. A determined Egyptian-American high-school athlete in a lacrosse helmet mid-shot, stick whipping forward, under Friday-night stadium lights in suburban Michigan. Dynamic action lines, sparks of neon cyan on the ball. Football and wrestling gear visible on a bench in the background.",
      },
      {
        id: "p04",
        where: "queens",
        size: "two-thirds",
        tag: "Cape Town → New York",
        scene: "A cricket bat in the Bronx",
        art: null,
        alt: "A teenage Mamdani swings a cricket bat on a Bronx field, the city skyline behind him.",
        captions: [
          { text: "At five, his family moves to Cape Town. At seven, New York City.", pos: "tl" },
          { text: "At Bronx Science he co-founds the school's first cricket team.", pos: "bl" },
        ],
        sfx: { text: "THWACK!" },
        cites: [1, 2],
        prompt: "Wide 2:1. Split background: Table Mountain in Cape Town fading into the New York skyline. In the foreground a skinny South Asian teenager in cricket whites swings a bat on a patchy Bronx field, ball exploding off the bat with speed lines. Gold sunset light, magenta and cyan rim light.",
      },
      {
        id: "p05",
        where: "detroit",
        size: "third",
        tag: "Ann Arbor · 2007",
        scene: "Commencement",
        art: null,
        alt: "El-Sayed at a podium in a graduation gown.",
        captions: [{ text: "University of Michigan, class of 2007. He gives the student commencement speech.", pos: "tl" }],
        bubbles: [{ who: "El-Sayed", text: "The person who leaves here today is better than the one who came.", pos: "center low" }],
        cites: [5],
        prompt: "Square 1:1. A young Egyptian-American graduate in a black gown and maize-and-blue stole speaks at a podium, huge stadium crowd behind him in the rain of confetti. Low heroic angle, gold and blue light.",
      },
    ],
  },
  {
    label: "Part 2",
    chapter: "The training arc",
    panels: [
      {
        id: "p06",
        where: "detroit",
        size: "wide",
        tag: "Oxford · New York",
        scene: "Rhodes Scholar, doctor, professor",
        art: null,
        alt: "A montage: Oxford spires, a Columbia white coat, an epidemiology lecture hall.",
        captions: [
          { text: "Rhodes Scholar. A doctorate in population health at Oxford. An M.D. from Columbia.", pos: "tl" },
          { text: "Then a professor of epidemiology at Columbia, studying how poverty makes people sick.", pos: "br" },
        ],
        cites: [5, 6, 7],
        prompt: "Wide 16:9 montage in three overlapping beats, left to right: the spires of Oxford at dusk with a young man in an academic gown; the same man pulling on a white doctor's coat in a New York hospital corridor; the same man at a chalkboard covered in charts and maps of a city, lecturing. One continuous figure, gold-to-cyan lighting gradient.",
      },
      {
        id: "p07",
        where: "queens",
        size: "half",
        tag: "Maine → Queens",
        scene: "Mr. Cardamom",
        art: null,
        alt: "Mamdani on a Jackson Heights street with his grandmother in a music video.",
        captions: [
          { text: "Bowdoin College, Africana Studies, 2014. Then a detour: rapping as \"Mr. Cardamom.\"", pos: "tl" },
          { text: "His 2019 video \"Nani\" stars Madhur Jaffrey as his grandmother.", pos: "bl" },
        ],
        cites: [2, 8],
        prompt: "Landscape 4:3. A young South Asian man in a bright tracksuit raps on a busy Jackson Heights, Queens street under the elevated 7 train, beside a regal elderly Indian grandmother in a sari who is clearly the star. Halal cart steam, colorful shop signs (no readable words), playful magenta and gold lighting.",
      },
      {
        id: "p08",
        where: "queens",
        size: "half",
        tag: "Queens",
        scene: "The kitchen table",
        art: null,
        alt: "Mamdani at a family's kitchen table going over foreclosure papers.",
        captions: [
          { text: "He becomes a housing counselor at Chhaya CDC in Queens, helping homeowners fight foreclosure.", pos: "tl" },
          { text: "That job is why he runs for office.", pos: "br" },
        ],
        cites: [9, 10],
        prompt: "Landscape 4:3. Night, a small Queens kitchen. A young South Asian housing counselor leans over a table of papers and envelopes with an anxious immigrant family, pointing to a line on a form. Warm lamp light against the cold blue window. Quiet, determined mood.",
      },
    ],
  },
  {
    label: "Part 3",
    chapter: "First fights",
    panels: [
      {
        id: "p09",
        where: "detroit",
        size: "wide",
        splash: true,
        tag: "Detroit · 2015",
        scene: "Rebuild it",
        art: null,
        alt: "El-Sayed walks into a nearly empty Detroit Health Department office.",
        captions: [
          { text: "2015. Detroit's health department had been gutted and privatized. What's left: five city employees and 85 contractors.", pos: "tl" },
          { text: "Mayor Mike Duggan hands the job to a 30-year-old epidemiologist. His orders: rebuild it.", pos: "bl" },
        ],
        cites: [11, 12],
        prompt: "Wide 16:9 splash. A young Egyptian-American man in a suit and loosened tie walks into a nearly empty, dusty Detroit city office: overturned chairs, dead fluorescent lights, a few boxes. Morning light cuts through tall windows onto him like a spotlight. Detroit's east-side skyline through the glass. Heroic low angle, gold light, deep blue shadows.",
      },
      {
        id: "p10",
        where: "detroit",
        size: "third",
        tag: "Detroit schools",
        scene: "Glasses for kids",
        art: null,
        alt: "A Detroit kid tries on new glasses in a mobile eye clinic.",
        captions: [{ text: "2016: free eye exams and free glasses for Detroit schoolkids, through a mobile clinic.", pos: "tl" }],
        cites: [13],
        prompt: "Square 1:1. Inside a mobile eye-clinic van parked outside a Detroit school, a grinning Black schoolgirl puts on her first pair of glasses and sees clearly; the blurry world behind her snaps into focus. Bright, joyful cyan and gold.",
      },
      {
        id: "p11",
        where: "detroit",
        size: "third",
        tag: "Detroit",
        scene: "SisterFriends",
        art: null,
        alt: "Volunteer mentors with a new mother and her baby.",
        captions: [{ text: "His push on infant deaths leads to SisterFriends Detroit: mentors for new moms through the baby's first birthday.", pos: "tl" }],
        cites: [14],
        prompt: "Square 1:1. A young Detroit mother holding her baby on a porch, surrounded by two smiling volunteer women mentors with a bag of baby supplies. Warm sunrise light, soft magenta glow.",
      },
      {
        id: "p12",
        where: "detroit",
        size: "third",
        tag: "Michigan · 2018",
        scene: "The first run",
        art: null,
        alt: "El-Sayed on stage at a rally, Bernie Sanders beside him.",
        captions: [
          { text: "2018: he runs for governor on single-payer health care. Bernie Sanders and AOC campaign with him.", pos: "tl" },
          { text: "He loses the primary. He doesn't quit.", pos: "bl" },
        ],
        cites: [15, 16, 17],
        prompt: "Square 1:1. A packed Michigan rally at night, confetti and phone lights. A young Egyptian-American candidate raises a fist at the mic; a white-haired older senator in a rumpled suit claps beside him. Then a hint of rain starting. Magenta and cyan stage light.",
      },
      {
        id: "p13",
        where: "queens",
        size: "half",
        tag: "Astoria · 2020",
        scene: "The upset",
        art: null,
        alt: "Mamdani canvassing in Astoria.",
        captions: [{ text: "2020: he knocks out a ten-year incumbent in Astoria by about 300 votes and goes to the State Assembly.", pos: "tl" }],
        sfx: { text: "UPSET!" },
        cites: [18],
        prompt: "Landscape 4:3. A young South Asian man with a clipboard knocks on the door of an Astoria, Queens row house under the elevated N train at night, volunteers behind him with flyers. Street lamps and neon bodega light, energetic mood.",
      },
      {
        id: "p14",
        where: "queens",
        size: "half",
        tag: "New York · 2023",
        scene: "Free buses",
        art: null,
        alt: "A packed city bus riding free.",
        captions: [{ text: "He fights for a fare-free bus pilot. On five routes, ridership jumps about 30% on weekdays.", pos: "tl" }],
        cites: [19],
        prompt: "Landscape 4:3. A crowded blue-and-white New York City bus at dusk, riders of every age boarding through all doors, no fare box, big smiles. Motion blur on the street, cyan headlights, gold interior light.",
      },
      {
        id: "p15",
        where: "queens",
        size: "wide",
        splash: true,
        tag: "City Hall · 2021",
        scene: "Hunger strike",
        art: null,
        alt: "Taxi drivers and Mamdani on hunger strike outside City Hall at night.",
        captions: [
          { text: "October 2021. Taxi drivers are drowning in medallion debt. He joins their hunger strike outside City Hall and gets arrested sitting in Broadway.", pos: "tl" },
          { text: "Day 15: a deal. Loans are cut to a $170,000 cap, with payments around $1,122 a month.", pos: "br" },
        ],
        sfx: { text: "DAY 15" },
        cites: [20, 21],
        prompt: "Wide 16:9 splash. Night outside New York City Hall: a sidewalk encampment of older immigrant taxi drivers in jackets, folding chairs and blankets, yellow cabs lined up behind them honking. A thin young South Asian man sits among them, exhausted but unbowed. Rain, puddle reflections of yellow cab lights, magenta and cyan neon.",
      },
    ],
  },
  {
    label: "Part 4",
    chapter: "Long odds",
    panels: [
      {
        id: "p16",
        where: "detroit",
        size: "half",
        tag: "Detroit · 2020–2025",
        scene: "Back to work",
        art: null,
        alt: "El-Sayed at a microphone for his podcast, a copy of his book on the desk.",
        captions: [
          { text: "He writes Healing Politics, hosts the podcast America Dissected, and goes back to government as Wayne County's health director.", pos: "tl" },
        ],
        cites: [22, 23],
        prompt: "Landscape 4:3. Late night in a Detroit home studio: an Egyptian-American man in a sweater talks into a podcast microphone, a hardcover book on the desk, the Detroit skyline and the Guardian Building glowing through the window. Cozy gold light, cyan monitor glow.",
      },
      {
        id: "p17",
        where: "queens",
        size: "half",
        tag: "Manhattan · 2025",
        scene: "The long walk",
        art: null,
        alt: "Mamdani walking down Broadway at night.",
        captions: [{ text: "October 2024: he runs for mayor, polling in single digits. June 2025: he walks the length of Manhattan overnight.", pos: "tl" }],
        bubbles: [{ who: "Mamdani", text: "New Yorkers deserve a mayor they can see, hear, even yell at.", pos: "right low" }],
        cites: [24, 25],
        prompt: "Landscape 4:3. Summer night on an empty Manhattan avenue, a lone young South Asian man in sneakers and rolled sleeves walks toward the camera, followers with phones trailing behind, skyscrapers glowing magenta and gold, steam rising from a manhole.",
      },
      {
        id: "p18",
        where: "queens",
        size: "wide",
        splash: true,
        tag: "New York · 2025",
        scene: "Hope is alive",
        art: null,
        alt: "Mamdani on stage on election night, arms raised, confetti falling.",
        captions: [
          { text: "June 2025: he beats Andrew Cuomo in the Democratic primary, 56% to 44%.", pos: "tl" },
          { text: "November 4: elected mayor. New York's first Muslim mayor, first South Asian mayor, first African-born mayor.", pos: "bl" },
        ],
        bubbles: [{ who: "Mamdani", text: "Hope is alive!", pos: "right high", shout: true }],
        cites: [26, 27, 28],
        prompt: "Wide 16:9 splash. Election night in a packed Brooklyn venue: a young South Asian man in a dark suit raises both arms at the podium, a sea of cheering supporters, confetti and phone lights, huge gold and magenta stage lighting. Ecstatic, triumphant.",
      },
      {
        id: "p19",
        where: "queens",
        size: "half",
        tag: "City Hall station · Jan 1, 2026",
        scene: "The oath",
        art: null,
        alt: "Mamdani sworn in at midnight in the old City Hall subway station.",
        captions: [{ text: "Just after midnight, January 1, 2026, he takes the oath in the old City Hall subway station.", pos: "tl" }],
        bubbles: [{ who: "Mamdani", text: "Never will we be accused of lacking the courage to try.", pos: "center low" }],
        cites: [29, 30],
        prompt: "Landscape 4:3. The decommissioned City Hall subway station at midnight: curved Guastavino tile arches, brass chandeliers, skylights. A young South Asian man in a dark coat raises his right hand, left hand on two Qurans held by his wife; a small circle of witnesses. Glowing gold and green tile light.",
      },
      {
        id: "p20",
        where: "detroit",
        size: "half",
        tag: "Michigan · 2025",
        scene: "Receipts",
        art: null,
        alt: "El-Sayed launching his Senate campaign.",
        captions: [{ text: "April 2025: he launches a run for U.S. Senate with a staff of four. Bernie Sanders endorses within hours.", pos: "tl" }],
        bubbles: [{ who: "El-Sayed", text: "If you want a fighter, I've got receipts.", pos: "right low" }],
        cites: [31, 32],
        prompt: "Landscape 4:3. A small rented Detroit campaign office at night, folding tables, four staffers on laptops, a hand-painted banner (no readable text). An Egyptian-American man in rolled shirtsleeves grins and holds up a fistful of paper receipts. Gold desk lamps, cyan laptop glow.",
      },
    ],
  },
  {
    label: "Part 5",
    chapter: "Landing punches",
    panels: [
      {
        id: "p21",
        where: "queens",
        size: "two-thirds",
        tag: "New York · June 2026",
        scene: "Rent freeze",
        art: null,
        alt: "Tenants cheering outside a Rent Guidelines Board vote.",
        captions: [
          { text: "June 25, 2026: the Rent Guidelines Board freezes the rent. 0% on one-year and two-year leases, for about a million rent-stabilized apartments.", pos: "tl" },
        ],
        bubbles: [{ who: "Mamdani", text: "A historic victory for New York City tenants.", pos: "left low" }],
        sfx: { text: "FROZEN!" },
        cites: [33],
        prompt: "Wide 2:1. Outside a hearing room, a crowd of New York tenants of every age cheers and hugs, homemade signs (no readable text), frost and ice crystals shattering across the frame for a 'freeze' effect. Cyan ice, gold and magenta light.",
      },
      {
        id: "p22",
        where: "queens",
        size: "third",
        tag: "New York · 2026",
        scene: "2-K",
        art: null,
        alt: "Toddlers in a bright new classroom.",
        captions: [{ text: "Free, full-day child care for two-year-olds, starting this September.", pos: "tl" }],
        cites: [34],
        prompt: "Square 1:1. A bright New York classroom full of two-year-olds painting and stacking blocks, a parent waving goodbye at the door with relief. Warm, joyful gold and pink light.",
      },
      {
        id: "p23",
        where: "queens",
        size: "third",
        tag: "East Harlem · Hunts Point",
        scene: "City grocery",
        art: null,
        alt: "A city-owned grocery store under construction.",
        captions: [{ text: "The first sites for city-owned grocery stores: La Marqueta in East Harlem and The Peninsula in Hunts Point.", pos: "tl" }],
        cites: [35],
        prompt: "Square 1:1. La Marqueta in East Harlem under the elevated Park Avenue railroad viaduct at dusk, market stalls being built out, crates of fresh produce, construction lights. Gold and magenta.",
      },
      {
        id: "p24",
        where: "queens",
        size: "two-thirds",
        tag: "New York · Sept 2026",
        scene: "Delivery workers get paid",
        art: null,
        alt: "Delivery workers on e-bikes in the rain, a giant check behind them.",
        captions: [{ text: "September 2026: the city wins a record $131.5 million from DoorDash for about 260,000 underpaid delivery workers.", pos: "tl" }],
        sfx: { text: "PAID!" },
        cites: [36],
        prompt: "Wide 2:1. A line of food-delivery workers on e-bikes in the rain on a New York avenue, insulated bags on their backs, raising fists and cheering as gold coins rain down around them. Neon storefront reflections, cyan and gold.",
      },
      {
        id: "p25",
        where: "detroit",
        size: "wide",
        splash: true,
        tag: "Michigan · Aug 4, 2026",
        scene: "The primary",
        art: null,
        alt: "El-Sayed on primary night in Detroit, arms raised.",
        captions: [
          { text: "August 4, 2026. Nearly $65 million in outside money pours into the Democratic Senate primary, most of it against him.", pos: "tl" },
          { text: "He wins by fewer than 15,000 votes. His opponents endorse him the next day.", pos: "bl" },
        ],
        sfx: { text: "WON!" },
        cites: [37, 38],
        prompt: "Wide 16:9 splash. Primary night in Detroit: an Egyptian-American man in a dark suit bursts through a wall of floating dollar bills and attack-ad TV screens, fists raised, cheering crowd behind him. Detroit skyline and the Renaissance Center glowing magenta and gold. Explosive, triumphant.",
      },
    ],
  },
  {
    label: "Part 6",
    chapter: "Same street",
    panels: [
      {
        id: "p26",
        where: "both",
        size: "wide",
        splash: true,
        tag: "The road to the Capitol",
        scene: "Two roads meet",
        art: null,
        alt: "Mamdani and El-Sayed walk side by side up a rain-slick avenue toward the Capitol.",
        captions: [
          { text: "One already runs the biggest city in America.", pos: "tl" },
          { text: "One faces Republican Mike Rogers for U.S. Senate on November 3, 2026. The fight isn't over.", pos: "bl" },
        ],
        cites: [39],
        prompt: "Wide 16:9 splash, matching the fighter-select screen: a rain-slick avenue at night leading to the lit U.S. Capitol dome. Seen from behind and slightly to the side, Zohran Mamdani (dark suit, polka-dot tie) and Abdul El-Sayed (black henley) walk side by side toward the Capitol, puddles reflecting neon magenta, cyan and gold. Epic, hopeful, cinematic.",
      },
    ],
  },
];

export const PLANKS = [
  { where: "queens", who: "Mamdani", title: "Freeze the rent", cites: [33, 40], text: "No rent increases for rent-stabilized tenants. The 2026 freeze covers about a million apartments." },
  { where: "queens", who: "Mamdani", title: "Fast and free buses", cites: [40], text: "End fares on city buses, and speed them up with more bus lanes and all-door boarding." },
  { where: "queens", who: "Mamdani", title: "Universal child care", cites: [40], text: "Free child care for every New York kid from six weeks to five years old." },
  { where: "queens", who: "Mamdani", title: "City-owned groceries", cites: [40], text: "A public grocery store in every borough." },
  { where: "queens", who: "Mamdani", title: "$30 minimum wage", cites: [40], text: "Raise the city's minimum wage to $30 an hour by 2030." },
  { where: "queens", who: "Mamdani", title: "Tax the top", cites: [40], text: "A 2% city income tax on earnings over $1 million, and a higher corporate tax rate." },
  { where: "detroit", who: "El-Sayed", title: "Medicare for All", cites: [41], text: "Cover every American from cradle to grave, including vision, dental and hearing, with no premiums, copays or deductibles." },
  { where: "detroit", who: "El-Sayed", title: "Money out of politics", cites: [41], text: "Never a dime of corporate PAC money. Overturn Citizens United and cap campaign spending." },
  { where: "detroit", who: "El-Sayed", title: "Put money in your pocket", cites: [41], text: "His campaign's promise: take on the costs that make it \"just too hard to get by\" in Michigan." },
  { where: "detroit", who: "El-Sayed", title: "Data centers on our terms", cites: [42], text: "\"All union jobs. No rate hikes. Improve our reliability. Don't touch our water.\"" },
  { where: "detroit", who: "El-Sayed", title: "Shut down Line 5", cites: [43], text: "Close the aging oil pipeline under the Straits of Mackinac." },
];

export const SOURCES = [
  { n: 1, label: "CNN, Zohran Mamdani fast facts.", url: "https://www.cnn.com/politics/zohran-mamdani-fast-facts" },
  { n: 2, label: "The Africa Report, 10 things about Zohran Mamdani.", url: "https://www.theafricareport.com/386712/zohran-mamdani-10-things-about-uganda-born-democratic-nominee-for-new-york-city-mayor/" },
  { n: 3, label: "Bridge Michigan, who is Abdul El-Sayed.", url: "https://bridgemi.com/michigan-government/who-is-abdul-el-sayed-what-to-know-about-michigan-democrats-us-senate-winner/" },
  { n: 4, label: "El-Sayed for Senate, about.", url: "https://abdulforsenate.com/about/" },
  { n: 5, label: "University of Michigan Record, Rhodes Scholar announcement.", url: "https://record.umich.edu/articles/u-m-dual-md-phd-student-named-rhodes-scholar/" },
  { n: 6, label: "Columbia Medicine, alumni profile.", url: "https://www.vagelos.columbia.edu/about-us/columbia-medicine-magazine/archives/fall-winter-2016/alumni-news-notes/alumni-profile-abdul-el-sayed14" },
  { n: 7, label: "Columbia Mailman School, El-Sayed takes health reins in Detroit.", url: "https://www.publichealth.columbia.edu/news/mailmans-el-sayed-takes-health-reins-detroit" },
  { n: 8, label: "Vice, Madhur Jaffrey stars in \"Nani.\"", url: "https://www.vice.com/en/article/madhur-jaffrey-nani-rap-video/" },
  { n: 9, label: "Brick Underground, housing counselors at Chhaya.", url: "https://www.brickunderground.com/live/how-owners-facing-foreclosure-get-help-housing-counselors-chhaya-mamdani" },
  { n: 10, label: "PBS NewsHour, how Mamdani rose from Queens lawmaker to mayor.", url: "https://www.pbs.org/newshour/politics/how-zohran-mamdani-rose-from-queens-lawmaker-to-mayor-of-new-york" },
  { n: 11, label: "STAT, Detroit's health director.", url: "https://www.statnews.com/2016/05/03/detroit-health-director/" },
  { n: 12, label: "American Rhodes Scholars, El-Sayed named Detroit health director.", url: "https://www.americanrhodes.org/news-1071.html" },
  { n: 13, label: "WDET, free eye exams and glasses for DPSCD students.", url: "https://wdet.org/posts/2016/10/12/83985-new-program-provides-free-eye-exam-and-glasses-to-dpscd-students" },
  { n: 14, label: "City of Detroit, infant mortality drop and SisterFriends.", url: "https://detroitmi.gov/news/mayor-duggan-and-dr-khaldun-announce-historic-drop-infant-mortality-rate-city-detroit-2019-had" },
  { n: 15, label: "Detroit News, El-Sayed's MichCare plan.", url: "https://www.detroitnews.com/story/news/local/michigan/2018/06/06/el-sayed-universal-health-michigan/677394002/" },
  { n: 16, label: "WKAR, Bernie Sanders endorses El-Sayed.", url: "https://www.wkar.org/politics-government/2018-07-26/bernie-sanders-endorses-el-sayed-in-michigans-governors-race" },
  { n: 17, label: "Bridge Michigan, Whitmer wins 2018 primary.", url: "https://bridgemi.com/michigan-government/gretchen-whitmer-wins-democratic-primary-michigan-governor/" },
  { n: 18, label: "PoliticsNY, Mamdani unseats Simotas.", url: "https://politicsny.com/2020/07/22/dsa-backed-mamdani-unseats-simotas-in-36-ad-race/" },
  { n: 19, label: "MTA, fare-free bus pilot report.", url: "https://www.mta.info/document/177466" },
  { n: 20, label: "THE CITY, cabbies go on hunger strike.", url: "https://www.thecity.nyc/2021/10/21/nyc-cabbies-go-on-hunger-strike-taxi-medallion-debts/" },
  { n: 21, label: "City & State, taxi drivers' victory.", url: "https://www.cityandstateny.com/politics/2021/11/activist-lawmakers-share-taxi-drivers-victory/186641/" },
  { n: 22, label: "Abrams Books, Healing Politics.", url: "https://www.abramsbooks.com/product/healing-politics_9781683358138/" },
  { n: 23, label: "Wayne County, El-Sayed joins Health, Human & Veterans Services.", url: "https://www.waynecountymi.gov/News/Executive/2022/Dr.-Abdul-El-Sayed-joins-Health-Human-Veterans-Services-Department" },
  { n: 24, label: "Hell Gate, Mamdani goes the distance.", url: "https://hellgatenyc.com/zohran-mamdani-goes-the-distance/" },
  { n: 25, label: "Zohran Mamdani on X, after the Manhattan walk.", url: "https://x.com/ZohranKMamdani/status/1937133937316233269" },
  { n: 26, label: "amNY, ranked-choice primary results.", url: "https://www.amny.com/news/mamdani-democratic-primary-ranked-choice-vote-win/" },
  { n: 27, label: "NBC News, New York City mayor results.", url: "https://www.nbcnews.com/politics/2025-elections/new-york-city-mayor-results" },
  { n: 28, label: "TIME, Mamdani's victory speech.", url: "https://time.com/7331243/watch-zohran-mamdani-victory-speech/" },
  { n: 29, label: "CBS New York, swearing-in at the old City Hall station.", url: "https://www.cbsnews.com/newyork/news/zohran-mamdani-swearing-in-old-city-hall-station/" },
  { n: 30, label: "NYC Mayor's Office, inaugural address.", url: "https://www.nyc.gov/mayors-office/news/2026/01/mayor-zohran-mamdani-inaugural-address" },
  { n: 31, label: "Michigan Advance, El-Sayed enters U.S. Senate race.", url: "https://michiganadvance.com/2025/04/17/el-sayed-enters-race-for-michigans-u-s-senate-seat/" },
  { n: 32, label: "Bridge Michigan, \"If you want a fighter, I've got receipts.\"", url: "https://bridgemi.com/michigan-government/abdul-el-sayed-us-senate-run-if-you-want-fighter-ive-got-receipts/" },
  { n: 33, label: "Gothamist, Rent Guidelines Board approves rent freeze.", url: "https://gothamist.com/news/nyc-rent-guidelines-board-approves-2-year-rent-freeze-fulfilling-mamdani-campaign-pledge" },
  { n: 34, label: "NYC Mayor's Office, first 2-K communities.", url: "https://www.nyc.gov/mayors-office/news/2026/03/mayor-mamdani-and-governor-hochul-announce-first-four-communitie" },
  { n: 35, label: "TIME, city-owned grocery stores.", url: "https://time.com/article/2026/05/21/mamdani-city-owned-grocery-stores-east-harlem-manhattan-the-bronx/" },
  { n: 36, label: "NYC Mayor's Office, $131.5 million from DoorDash.", url: "https://www.nyc.gov/mayors-office/news/2026/09/mayor-mamdani-wins-record--131-5-million-from-doordash-for-deliv" },
  { n: 37, label: "Michigan Advance, El-Sayed wins the Senate primary.", url: "https://michiganadvance.com/2026/08/05/abdul-el-sayed-squeaks-out-win-over-haley-stevens-in-hotly-contested-democratic-us-senate-primary/" },
  { n: 38, label: "CNBC, Michigan Senate primary.", url: "https://www.cnbc.com/2026/08/04/abdul-el-sayed-haley-stevens-michigan-primary.html" },
  { n: 39, label: "Washington Post, Michigan Senate poll.", url: "https://www.washingtonpost.com/politics/2026/09/17/michigan-senate-race-poll-finds-abdul-el-sayed-has-narrow-edge-over-mike-rogers/" },
  { n: 40, label: "Zohran for NYC, platform.", url: "https://zohranfornyc.com/" },
  { n: 41, label: "El-Sayed for Senate, priorities.", url: "https://abdulforsenate.com/priorities/" },
  { n: 42, label: "El-Sayed on X, data center terms.", url: "https://x.com/AbdulElSayed/status/2028267127837233314" },
  { n: 43, label: "Bridge Michigan, where the candidates stand on Line 5.", url: "https://bridgemi.com/michigan-government/line-5-where-jocelyn-benson-john-james-abdul-el-sayed-mike-rogers-stand/" },
];
